### ISSUE TITLE
KCP ModuleConfig

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1104]
Created on 2023-12-03 by Xin Ruan (@ruanxin)

## Decision log

| Name               | Description            |
| ------------------ | ---------------------- |
| Title              | KCP ModuleConfig     |
| Due date           | 2023-12-30             |
| Status             | Proposed on 2023-12-03 |
| Decision type      | Binary                 |
| Affected decisions | -                      |
 
## Context

For certain [SyncResource](https://github.com/kyma-project/lifecycle-manager/issues/991) to be deployed into remote Kyma runtime, it relies on the configuration data configured by the end user in Kyma runtime. However, the Module Manager which produce SyncResource is deployed in KCP, in order to offer Module Manager this configuration data, a strategy must provided to copy it from Kyma runtime to KCP, the detail SDD document please check [here](https://github.com/kyma-project/community/pull/856). This decision record is to define the ModuleConfig CR in KCP which used to persist the configuration data. 

## Decision

- Introduce ModuleConfig to persist module configuration data, and it's deployed in KCP.
- ModuleConfig must provide a way to let related Module Manager filter content which belongs to it.
- Module CR in Kyma runtime is the only source to provide the required configuration data for Module Manager to consume.
- Lifecycle Manager is the producer for ModuleConfig. The content is collected from related Module CR. When Module CR is created or updated, the lifecycle manager will update the related ModuleConfig in KCP.

### KCP ModuleConfig example:

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleConfig
metadata:
  labels:
    "operator.kyma-project.io/kyma-name": [related kyma name]
    "operator.kyma-project.io/module-name": [related module name]
  name: [unique name]
  namespace: kcp-system
spec:
  kyma: [related kyma name]
  module: [related kyma name]
  resource: |
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Infrastructure
      metadata:
        name: default
        namespace: kyma-system
      spec:
        vpcPeerings:
          - name: peering-1
            description: peering-1
            remoteVpcId: vpc-1
            remoteRegion: eu-central-1
            remoteCidrRange:
          - name: peering-2
            description: peering-2
            remoteVpcId: vpc-2
            remoteRegion: eu-central-1
            remoteCidrRange:
        nfsVolumes:
          - name: nfs-1
            description: nfs-1
            size: 100Gi
          - name: nfs-2
            description: nfs-2
            size: 100Gi
       status:
          ...
          state: Ready   
Status:
  conditions:
  - lastTransitionTime: "2023-10-30T15:56:31Z"
    message: module config has been synced
    reason: Ready
    status: True
    type: ModuleConfig
  lastOperation:
    lastUpdateTime: "2023-10-30T15:56:31Z"
    operation: 'module config successfully synced from skr'
  state: Ready
```
### KCP ModuleConfig explain:
- `operator.kyma-project.io/kyma-name` label enables the Module manager to identify the target Kyma runtime for deploying the resource.
- `operator.kyma-project.io/module-name` label provides the Module manager to filter the ModuleConfig which belongs to it.
- `spec.kyma` mandatory, specifies the target Kyma name where this module config comes from.
- `spec.module` mandatory, specifies which module this module config belongs to.
- `spec.resource` mandatory, contains the module CR YAML content as plain text, include subresource(status) field.
- `status.conditions` and `status.lastOperation` indicate the synchronization status and provide information about the last operation performed by the lifecycle manager.
- `status.state` reflects the current state of the synced Module Config.
- `status.resources` indicates the status of the current list of Resources been synced.
