### ISSUE TITLE
Validate uniqueness of listed modules with varying names

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1276]
### Description

Follow up from https://github.com/kyma-project/lifecycle-manager/issues/1242

We validate uniqueness of module names in `.spec.modules` based on the specified name. However, since we support multiple alternatives for specifying a module name, the same module can still be added multiple times when using the alternative names.

E.g. template operator can be added twice by specifying

```yaml
spec:
  modules:
  - name: template-operator
  - name: kyma-project.io/module/template-operator
```

<details>

<summary>Click here for examplary KymaCR as a result</summary>

```yaml
  Name:         default
  Namespace:    kyma-system
  Labels:       operator.kyma-project.io/watched-by=lifecycle-manager
  Annotations:  operator.kyma-project.io/owned-by: kcp-system/kyma-sample
  API Version:  operator.kyma-project.io/v1beta2
  Kind:         Kyma
  Metadata:
    Creation Timestamp:  2024-01-19T14:56:17Z
    Generation:          10
    Resource Version:    12605
    UID:                 7a30e000-8d9d-451a-afa1-b46e605336bf
  Spec:
    Channel:  regular
    Modules:
      Custom Resource Policy:  CreateAndDelete
      Name:                    kyma-project.io/module/template-operator
      Custom Resource Policy:  CreateAndDelete
      Name:                    template-operator
  Status:
    Active Channel:  regular
    Conditions:
      Last Transition Time:  2024-01-22T09:16:13Z
      Message:               all modules are in ready state
      Observed Generation:   1
      Reason:                Ready
      Status:                True
      Type:                  Modules
      Last Transition Time:  2024-01-22T09:16:13Z
      Message:               module templates are synchronized
      Observed Generation:   1
      Reason:                Ready
      Status:                True
      Type:                  ModuleCatalog
      Last Transition Time:  2024-01-22T09:16:13Z
      Message:               skrwebhook is synchronized
      Observed Generation:   1
      Reason:                Ready
      Status:                True
      Type:                  SKRWebhook
    Last Operation:
      Last Update Time:  2024-01-22T09:16:13Z
      Operation:         kyma is ready
    Modules:
      Channel:  regular
      Fqdn:     kyma-project.io/module/template-operator
      Manifest:
        API Version:  operator.kyma-project.io/v1beta2
        Kind:         Manifest
        Metadata:
          Generation:  1
          Name:        kyma-sample-template-operator-1125230537
          Namespace:   kcp-system
      Name:            kyma-project.io/module/template-operator
      Resource:
        API Version:  operator.kyma-project.io/v1alpha1
        Kind:         Sample
        Metadata:
          Name:       sample-yaml
          Namespace:  kyma-system
      State:          Ready
      Template:
        API Version:  operator.kyma-project.io/v1beta2
        Kind:         ModuleTemplate
        Metadata:
          Generation:  2
          Name:        template-operator-regular
          Namespace:   kcp-system
      Version:         0.1.0
      Channel:         regular
      Fqdn:            kyma-project.io/module/template-operator
      Manifest:
        API Version:  operator.kyma-project.io/v1beta2
        Kind:         Manifest
        Metadata:
          Generation:  1
          Name:        kyma-sample-template-operator-2235966007
          Namespace:   kcp-system
      Name:            template-operator
      Resource:
        API Version:  operator.kyma-project.io/v1alpha1
        Kind:         Sample
        Metadata:
          Name:       sample-yaml
          Namespace:  kyma-system
      State:          Ready
      Template:
        API Version:  operator.kyma-project.io/v1beta2
        Kind:         ModuleTemplate
        Metadata:
          Generation:  2
          Name:        template-operator-regular
          Namespace:   kcp-system
      Version:         0.1.0
    State:             Ready
  Events:              <none>
```

</details>

We need to consider handling/preventing this case.

### Reasons

Adding the same module twice is not explicitly supported so we should prevent this from being possible.

### Acceptance Criteria

- [ ] When adding the same module using alternative names twice to the module list
  - [ ] Then the API server refuses to update the `KymaCR`
  - [ ] Then I get an error message similar to the one when adding it twice under the same way
