### ISSUE TITLE
Investigation: GH-Action Pipeline to detect diff in Kustomize Setup

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1329]
### Description

Since we switched to Helm Charts on our landscape deployments, but we still stick to Kustomize in our OpenSource project, we need to create a Pipeline which "reminds" us to propagate Kustomize changes to our internal Helm charts.

### Reasons

- Reminder to propagate Setup changes to Helm charts
- Pipeline should only be green, if one Codeowner confirmed that Kustomize changes have been propagated to internal Helm Chart setup
- Hinders us to merge unwanted setup changes

### Acceptance Criteria

- [x] Investigate:
    - Is it possible to retrigger a PR-based GH-Action-Pipeline with an additional input-parameter
    - Should be possible the same way as it works with input-parameters for pipelines with manual trigger
    - If possible, continue with next ACs
    - If it is not working with additional input parameter then proper label should be set on the PR
- [x] Implement new GH-Action Pipeline
    - Pipeline should get triggered on PRs opened to `main` branch
    - Should render kustomize for main branch and for PR-branch; compare both; if no diff has been found; pipeline is green
    - If diff was found pipeline should be red
    - If pipeline was red, and then retriggered with input parameter set to `Changes Propagated = True`, then Pipeline is green, eventho diff have been detected

**Comment by c-pius** [comment]
> Is it possible to retrigger a PR-based GH-Action-Pipeline with an additional input-parameter

I am afraid this is not possible. At least from the answers [here](https://stackoverflow.com/questions/63288356/how-to-link-a-github-actions-manual-run-to-a-pr) (question is different but answers seem to apply to our case as well) it doesn't seem possible. Also, we have a similar setup with our TestSuite E2E. TestSuite E2E has PR and Workflow triggers. Looking at the PR checks, we don't find the option to re-trigger the check based on the manual workflow dispatch. We can only re-trigger via standard "re-run" jobs. When looking at the Actions tab, we find the manual trigger for TestSuite E2E, but the question is how this trigger would link the run to the PR (as also mentioned on the stack question above and [here](https://stackoverflow.com/questions/76464269/how-to-rerun-a-github-action-workflow-from-the-command-line-and-have-the-status)). It may be possible to add the latest commit hash of the PR as argument, or to build some scripting that looks this up from a passed PR number. But both seem inpractical.

Therefore looking into a label-based alternative now.

**Comment by c-pius** [comment]
> If it is not working with additional input parameter then proper label should be set on the PR

### Rough idea

New mandatory pipeline

```yaml
name: "Verify kustomize diff"

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened", "labeled"] # first three are the default, we add when a label was added

jobs:
  run-kustomize-diff:
    if: !contains( github.event.pull_request.labels, 'confirm/helm-update') # we skip the verification and go green if the label is set
    # ...
    # steps...
    #   do the kustomize magic on main and PR head
    #   if no_diff:
    #     return green
    #   if diff:
    #     print: Diff detected, make sure helm is updated and add the "confirm/helm-update" label once okay
    #     return red
```

### Breakdown

We define a label like `confirm/helm-update`. With that label being present, the author explicitly acknowledges that a difference in the kustomize output is okay and possibly needed helm updates have been made. 

We define a job calculating the diffs (may even be multiple jobs). Important: we only run the job if the `confirm/helm-update` label is NOT present.

If it is run and there is a diff, we fail the job and print that the helm needs to be checked and label added once okay. If there is no diff, we succeed the job.

So on initial (normal) execution (opened, synchronized, reopened), the jobs will first fail if there is a diff. Then the dev can align the helm and explicitly add the `confirm/helm-update` label. Adding the label will trigger the execution again (`labeled` pr trigger type). The diff job will not execute again and pipeline goes green.

### Pros/Cons

```diff
- we re-trigger the job every time a label is added (even automatic ones)
+ simple to use
+ `confirm/helm-update` label will remain on the PR and we could use it at some point to search for PRs that potentially led to Helm updates
```
