### ISSUE TITLE
Module catalogue improvements

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1472]
### Description

Module catalogue (in this case - collection of Module Templates setup) should be adapted to the new requirements:
- A given module should be available in multiple different versions, users should be able to enable a specific version in their cluster. This requirement does not contradict the channel concept. It should still be possible to "subscribe" to a given channel (which will be one of the versions marked with that channel).
- Some module versions/channels use the same OCM descriptors, right now OCM part is embedded in the Module Template CR, which means there is no way to change/reference it across different resources. We should consider referencing that part instead of having that as a part of the Module Template spec. (We can use either [K8S resources](https://ocm.software/docs/component-descriptors/version-3/) or OCM repo URLs)
- For the restricted markets there should be an option to configure the repository from which manifests are fetched (i.e. China market will use the China-restricted repository).
- For each module, there should be a list of "domain CRDs" that this module brings (i.e. Serverless will have Functions, Istio will have Gateways, Virtual Services...) that can be used to see which CRDs correspond to which module.

As for the implementation options, there are two main ones:
- We could continue using Module Templates and have them extended according to the requirements. This, however, may be problematic from the "multiple versions" point of view.
- Have a central "registry" of the modules, just like in the [Community Modules repo](https://github.com/kyma-project/community-modules/blob/main/modules.js). We could aggregate them in a single list (with all the fields that we require) and then use a Config Map or a Secret mounted to the KLM pod.

### Reasons

We should adapt to the changing requirements and Community Modules concept.

### Acceptance Criteria

- Describe the **Module Catalogue**
  - When a new **Kyma Module** is added to the catalogue
    - Then a new entry in **Module Catalogue** is created
      - And the **Kyma Module** entry contains all available versions of that module
      - And each version of that **Kyma Module** references a template for the OCM Descriptor URL
      - And the **Kyma Module** entry contains a list of all **Module Domain CRDs** managed by that **Kyma Module**
      - And **Module Distribution Channels** are assigned to specific versions of that **Kyma Module**
- Describe the **Lifecycle Manager** behaviour
  - When a new **KCP Cluster** is created
  - And a configuration for **Manifest Repository** is created
    - Then **Lifecycle Manager** uses **Manifest Repository** to fill in OCM Descriptor templates in **Module Catalogue**  
      
### Open Questions
- What to do with the restricted OCM repository authentication regarding fetching manifest/resources
- Take into consideration the following tickets which may influence overall API shape:
  - https://github.com/kyma-project/lifecycle-manager/issues/1427
  - https://github.com/kyma-project/lifecycle-manager/issues/1211
  - https://github.com/kyma-project/lifecycle-manager/issues/1471

### Related Tickets
- https://github.com/kyma-project/lifecycle-manager/issues/1815 
- https://github.com/kyma-project/lifecycle-manager/issues/1816 
- https://github.com/kyma-project/lifecycle-manager/issues/1817 
- https://github.com/kyma-project/lifecycle-manager/issues/1831 
- https://github.com/kyma-project/lifecycle-manager/issues/1839 
- https://github.com/kyma-project/lifecycle-manager/issues/1840 
- https://github.com/kyma-project/lifecycle-manager/issues/1841 
- https://github.com/kyma-project/lifecycle-manager/issues/1842 
- https://github.com/kyma-project/lifecycle-manager/issues/1843 
- https://github.com/kyma-project/lifecycle-manager/issues/1477 
- https://github.com/kyma-project/lifecycle-manager/issues/1812
- https://github.com/kyma-project/lifecycle-manager/issues/1847
- https://github.com/kyma-project/lifecycle-manager/issues/1848
- https://github.com/kyma-project/lifecycle-manager/issues/1849
- https://github.com/kyma-project/lifecycle-manager/issues/1850
- https://github.com/kyma-project/lifecycle-manager/issues/1851
- https://github.com/kyma-project/modulectl/issues/53
- https://github.com/kyma-project/modulectl/issues/54
- https://github.com/kyma-project/modulectl/issues/55
- https://github.com/kyma-project/modulectl/issues/57
- https://github.com/kyma-project/modulectl/issues/62
- https://github.com/kyma-project/lifecycle-manager/issues/2059
- https://github.com/kyma-project/modulectl/issues/113
- https://github.com/kyma-project/modulectl/issues/119
- https://github.com/kyma-project/lifecycle-manager/issues/2127

**Comment by jeremyharisch** [comment]
Acceptance Criteria for EPIC:
- [ ]  Research about the topic
- [ ] Think about a proper issue split for this EPIC
- [ ] Create Sub-Issues to cover the implementation
- [ ] Regarding business requirements talk to @janmedrek if needed

**Timebox:** 2 Days

**Comment by Tomasz-Smelcerz-SAP** [comment]
I think we should use K8s explicit types and avoid obscure solutions (like mounted ConfigMaps/Secrets) for the Module Catalogue.
That's why I propose to have the Module Catalogue defined as:
`Module Catalogue is a collection of Module Templates in the cluster the Lifecycle-Manger is deployed.`

**Comment by Tomasz-Smelcerz-SAP** [comment]
Requirement 1:
`A given module should be available in multiple different versions, users should be able to enable a specific version in their cluster. This requirement does not contradict the channel concept. It should still be possible to "subscribe" to a given channel (which will be one of the versions marked with that channel).`

Use case 1: User wants to enable a specific version of a module in their cluster.
```
[...]
- modules:
  - name: my-module
    version: 1.0.0
[...]
```

Use case 2: User wants to enable a specific channel of a module in their cluster.
```
[...]
- modules:
  - name: my-module
    channel: fast
[...]
```

API Changes:
- Kyma CR type: We need a new optional `version` attribute in the Module list. The `channel` attribute should be optional as well. User must provide either the `version` or the `channel` attribute.
- ModuleTemplate CR type: Currently the module version is defined using an annotation: "operator.kyma-project.io/module-version". We need a new optional `version` attribute in the Module CR type. The reason for that is to make the version explicit in the ModuleTemplate CR type. In later API versions, this attribute should be mandatory.


Implementation details:

ModuleTemplate:

An example of current ModuleTemplate CR type (version is an annotation):

```
kind: ModuleTemplate
metadata:
  name: template-operator-regular
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "template-operator"
  annotations:
    "operator.kyma-project.io/doc-url": "https://kyma-project.io"
    "operator.kyma-project.io/is-cluster-scoped": "false"
    "operator.kyma-project.io/module-version": "0.1.2" 
spec:
  channel: regular
  version: 0.1.2
  mandatory: false 
  data:
  [...]
  descriptor:
  [...]
```

An example of the new ModuleTemplate CR type with the version attribute:
```
kind: ModuleTemplate
metadata:
  name: template-operator-regular
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "template-operator"
  annotations:
    "operator.kyma-project.io/doc-url": "https://kyma-project.io"
    "operator.kyma-project.io/is-cluster-scoped": "false"
spec:
  channel: regular
  version: 0.1.2
  mandatory: false 
  data:
  [...]
  descriptor:
  [...]
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
### Modified channel/version design:

At this moment we only allow users to select the `channel`.
After the change, the user will also be able to select the `version`.
for that to work, the `version` must refer to a unique ModuleTemplate.
I propose to make the following changes in the ModuleTemplate API:
- drop the "channel" attribute
- add the "channels" attribute
- add the "version" attribute

Example:

1. A module version defined in the "regular" channel 
```
kind: ModuleTemplate
[...]
spec:
  channels: ["regular"]
  version: 0.1.1
```

2. A module version defined in two channels:
```
kind: ModuleTemplate
[...]
spec:
  channels: ["regular", "fast"]
  version: 0.1.2
```

3. A standalone module version (no channel):
```
kind: ModuleTemplate
[...]
spec:
  channels: []
  version: 0.1.3
```

### Module management considerations:
What if the team releases a module version as standalone, and later wants to publish it in the `fast` channel? Similarly - what if the team initially publishes a module version in `fast` channel and later on decides to publish it also in the `regular` channel?
We have two options here:
1. Somehow we allow the `channels` attribute to be modified in the ModuleTemplate
2. The team must release a new version for that purpose, referring to the same OCM artifact(s)

I opt for option 2. as it simplifies module management - as ModuleTemplates are immutable, it's simpler to distribute/cache them.

**Comment by Tomasz-Smelcerz-SAP** [comment]
### Modified channel/version design option 2:

At this moment we only allow users to select the `channel`.
After the change, the user will also be able to select the `version`.
for that to work, the `version` must refer to a unique ModuleTemplate.
I propose to make the following changes in the ModuleTemplate API:
- drop the "channel" attribute
- add the "channels" attribute
- add the "version" attribute

Example:

1. A module version defined in the "regular" channel 
```
kind: ModuleTemplate
[...]
spec:
  channels: ["regular"]
  version: 0.1.1
```

2. A module version defined in two channels:
```
kind: ModuleTemplate
[...]
spec:
  channels: ["regular", "fast"]
  version: 0.1.2
```

3. A standalone module version (no channel):
```
kind: ModuleTemplate
[...]
spec:
  channels: []
  version: 0.1.3
```

### Module management considerations:
What if the team releases a module version as standalone, and later wants to publish it in the `fast` channel? Similarly - what if the team initially publishes a module version in `fast` channel and later on decides to publish it also in the `regular` channel?
We have two options here:
1. Somehow we allow the `channels` attribute to be modified in the ModuleTemplate
2. The team must release a new version for that purpose, referring to the same OCM artifact(s)

I opt for option 2. as it simplifies module management - as ModuleTemplates are immutable, it's simpler to distribute/cache them.

**Comment by Tomasz-Smelcerz-SAP** [comment]
### Requirement 4
`For each module, there should be a list of "domain CRDs" that this module brings (i.e. Serverless will have Functions, Istio will have Gateways, Virtual Services...) that can be used to see which CRDs correspond to which module.`

This can be done during the ModuleTemplate creation. We can extends `modulectl create module` command (not yet existing) to parse the resources in order to find the CRDs. In addition we may allow user to explicitly add some CRDs manually.

#### The modified ModuleTemplate CR example:

```
kind: ModuleTemplate
metadata:
  name: kyma-istio
  namespace: kcp-system 
spec:
  version: 1.2.3
  mandatory: false
  domainCRDs:
  - apiVersion: "networking.istio.io/v1beta1"
    kind: "Gateway"
  - apiVersion: "networking.istio.io/v1beta1"
    kind: "VirtualService"
  [...]
```
