### ISSUE TITLE
[Deletion Modes] Introduce associatedResources field to Manifest Spec

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/lifecycle-manager#1582]
### Description

In order to support https://github.com/kyma-project/lifecycle-manager/issues/1211, we need to have the associatedResources saved in the ManifestSpec.

### Reasons

To support managed resources, we need the `associatedResources` field so that it can be used to determine which resources are managed and need to be deleted first from the SKR Cluster.

### Acceptance Criteria

- [x] Introduce optional AssociatedResources field to Manifest Spec 
- [x] Add corresponding Documentation

Example Manifest CR:

```yaml
[...]
spec:
  install:
    name: raw-manifest
    source:
      [...]
  remote: true
  resource:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Sample
    metadata:
      name: sample-yaml
      namespace: kyma-system
    spec:
      resourceFilePath: ./module-data/yaml
  associatedResources: 
     - serverless.kyma-project.io/v1alpha2/functions
     - operator.kyma-project.io/v1alpha1/serverlesses
  version: 1.1.1
```
