### ISSUE TITLE
[Module catalogue improvements ] Extend Kyma CR module list with an explicit version

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#1589]
### Description

**Note: This issue is just about API change, the change in the controller logic is expected to be implemented [here](https://github.com/kyma-project/lifecycle-manager/issues/1591)**

In order to support [explicit module version](https://github.com/kyma-project/lifecycle-manager/issues/1472), we need to add an optional `version` attribute to the  Kyma CR module list.

##### Use case 1 / existing: User wants to enable a module in their cluster with the default channel.
```
[...]
channel: regular
modules:
  - name: my-module
[...]
```

##### Use case 2 / existing: User wants to enable a specific channel of a module in their cluster.
```
[...]
modules:
  - name: my-module
    channel: fast
[...]
```

##### Use case 3 / new: User wants to enable a specific version of a module in their cluster.
```
[...]
modules:
  - name: my-module
    version: 1.0.0
[...]
```

### Reasons

We need this because users must be given an option to install a specific version of the module.
If the user wants to enable a specific module version, a ModuleTemplate CR corresponding to that version must exist in the control-plane.

### Acceptance Criteria

- [x] Add new optional `version` attribute is to the module list in Kyma CR, which must be a semantic version.
- [x] Add a validation: either `channel` or `version` is present - it is an error to provide both 
  - should be validated in the reconciliation loop and present an error in the state for the user
  - can open schema validation support such case? **No**
- [x] Add a validation that `channel` must not be set to `none`

#### Examples

```yaml
# KymaCR
spec:
  channel: regular
  modules:
    - name: template-operator
      version: 2.3.1
# => resolves to template-operator-2.3.1
---
# KymaCR
spec:
  channel: regular
  modules:
    - name: template-operator
# => resolves to template-operator-regular
---
# KymaCR
spec:
  channel: regular
  modules:
    - name: template-operator
      channel: fast
# => resolves to template-operator-fast
---
# KymaCR
spec:
  channel: regular
  modules:
    - name: template-operator
      channel: fast
      version: 2.3.1
# => ERROR: must not have both channel and version set
---
# KymaCR
spec:
  channel: regular
  modules:
    - name: template-operator
      channel: none
# => ERROR: must not use none as a value
```

### Feature Testing
e2e test for the validation. Can be done with local EnvTest.

### Related issue(s)
https://github.com/kyma-project/lifecycle-manager/issues/1590
