### ISSUE TITLE
[Module catalogue improvements] Update ModuleTemplate API version to support fixed module versions

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#1590]
### Description

**Note: This issue is just about API change, the change in the controller logic is expected to be implemented [here](https://github.com/kyma-project/lifecycle-manager/issues/1591)**

As described [here](https://github.com/kyma-project/lifecycle-manager/issues/1472), ModuleTemplate CR must be extended.

What we essentially want follows the ideas from the [community-modules](https://raw.githubusercontent.com/kyma-project/community-modules/4067085235bdb3519a9f593b9c473106471e200e/model.json) repository.
In general, we want that:
- Every ModuleTemplate describes a single module version
- Every such version may be selected by user(s) for installation
- Every such version may be assigned to a set of channels - possibly empty. Module Team decides about versions-channels mapping.

In addition, to support [Deletion modes](https://github.com/kyma-project/lifecycle-manager/issues/1211) we need a `managedResources` list describing the list of Group/Version/Kinds that are defined by the Module's Team as "managed" by the module.
There is a [decision record for that](https://github.com/kyma-project/lifecycle-manager/issues/1587). Assuming that list is embedded, no further API changes are required on the ModuleTemplate CR. 

The set of ModuleTemplate CRs in the control-plane defines the Module Catalog for the Lifecycle-Manager.

The above requirements can be implemented by releasing a new ModuleTemplate API version with the following changes:
- Deprecate the `channel` attribute
- Add an optional `version` attribute. At the moment it is an annotation: `"operator.kyma-project.io/module-version": "0.1.2"`. This attribute will be required in the future
- Add an optional `name` attribute. At the moment it is a label: `"operator.kyma-project.io/module-name": "template-operator"`. It is not strictly required, it's just to make the API more robust. It will be required in the future.

### Reasons

We need that to support features described in #1472 

### The Data Model

Example: Consider a module: `foo`.
It will be released in two versions available for user to install: `1.0.0`, `2.0.0`.
Additionally there is a `2.2.0` version that is only available in the `experimental` channel.
The `1.0.0` is released in the `regular` channel, the `2.0.0` version is released in the `fast` channel

We need five ModuleTemplate CRs to model that:

1. ModuleTemplate for the version 1.0.0
```
name: "foo"
version: "1.0.0"
descriptor: [ OCM descriptor for version 1.0.0 ]
```

2. ModuleTemplate for the version 2.0.0
```
name: "foo"
version: "2.0.0"
descriptor: [ OCM descriptor for version 2.0.0 ]
```

3. ModuleTemplate for the `regular` channel
```
name: "foo"
version: "regular"
descriptor: [ OCM descriptor for version 1.0.0 ]
```

4. ModuleTemplate for the `fast` channel
```
name: "foo"
version: "fast"
descriptor: [ OCM descriptor for version 2.0.0 ]
```

5. ModuleTemplate for the `experimental` channel
```
name: "foo"
version: "experimental"
descriptor: [ OCM descriptor for version 2.2.0 ]
```

After some time, the team decides to upgrade the module in the `regular` channel and also make the version `2.2.0` explicitly available for users. In order to do that the module team must:

1. Update the ModuleTemplate for the `regular` channel:
```
name: "foo"
version: "regular"
descriptor: [ OCM descriptor for version 2.0.0 ]
```

2. Create a new ModuleTemplate for the `2.2.0` version:
```
name: "foo"
version: "2.2.0"
descriptor: [ OCM descriptor for version 2.2.0 ]
```

In this model, the channel is just another "version" to choose from. The channel doesn't refer to any other ModuleTemplate CR, it only references an OCM artifact - like any other version. It is responsibility of the Team that manages the module to take care that the ModuleTemplate with a __channel__ as a version refers to a proper OCM artifact. In other words the mapping of "channel" to "module version" is implicit here.
Yet, the desired feature of having a channel that is a "label" on a single module version is achieved. For example, a ModuleTemplate for some module that uses `regular` as a version may refer to the same OCM artifact as a ModuleTemplate for the same module that uses `1.0.0` as a version. It may also refer to the OCM artifact for which there is no explicit "versioned" ModuleTemplate, yet it is still some version - because it exists as an OCM artifact so it was released.

#### Single attribute vs two attributes
The same model can be expressed in two ways:
- having a single `version` attribute that can take values like `1.0.0`, `2.0.0`, `regular`, `fast` etc.
- having a separate `channel` attribute (`regular`, `fast`) and a separate `version` attribute (`1.0.0`, `2.0.0`) with additional validation that only one of these may be defined - the other one must be empty.

**A single attribute solution is simpler, but if this cannot be easily validated (a string that is either semantic version OR arbitrary token), the double-attribute solution is an option.**

### Summary

We have decided to go with the two-attribute solution described in [this comment](https://github.com/kyma-project/lifecycle-manager/issues/1590#issuecomment-2191526116).

No validation is required for now.

#### Examples for valid Module Templates

```yaml
# ModuleTemplate
metadata:
  name: template-operator-2.3.1
spec:
  moduleName: template-operator
  channel: none
  version: 2.3.1
---
# ModuleTemplate
metadata:
  name: template-operator-regular
spec:
  moduleName: template-operator
  channel: regular
  version: 2.3.1
---
# ModuleTemplate
metadata:
  name: template-operator-fast
spec:
  moduleName: template-operator
  channel: fast
  version: 2.3.1
```

### Acceptance Criteria

- [x] Extend the model with an optional `version` attribute. The value must be a semantic version.
- [x] `channel` attribute should stay mandatory.
- [x] Add an explicit optional `moduleName` attribute (currently it is a label).
- [x] Do not introduce new API version
- [x] Create a list of changes to include in a new ModuleTemplate API versions, i.e.,
  - [ ] `version` attribute to become mandatory
  - [ ] `moduleName` attribute to become mandatory

Notes:
In order to support existing ModuleTemplates, the version must be optional. Existing modules will have it empty.
New modules will have the version provided.
The same with the new moduleName attribute.
The implementation must deal with that correctly.

### Feature Testing
e2e tests for validation on the new API version.

### Related issue(s)
https://github.com/kyma-project/lifecycle-manager/issues/1472

**Comment by Tomasz-Smelcerz-SAP** [comment]
We may also consider to introduce a new CR: **ModuleVersion**, that would take over the existing ModuleTemplate
Reasons:
- The name better corresponds to the role the CR serves (it describes an entry in the Module Catalog for a given module version)
- Less confusion about how the "old" vs "new" ModuleTemplate works

**Comment by c-pius** [comment]
One thing we need to consider is how the installed module version shows in Busola. Right now, the module overview of a given Kyma shows the active channel and currently installed version of the module. If we remove the channel and use `regular` or `fast` version identifiers in the same way as we use the semantic versions, the user should still be able to see the exact version that is currently installed.

**Comment by c-pius** [comment]
Xin and myself discussed this a bit further...

> AC: Extend the model with a version attribute. the value must be a semantic version OR a channel reference: regular, fast, experimental etc. Alternatively, see the Single attribute vs two attributes note above.

If choosing a single-attribute approach, we should not name the field `version`. Values like `regular` or `fast` are not versions and have a special meaning. Rather name it `tag` or something different, **open for proposals**.

Note that in KymaCR, we would still go for separated `version` and `channel` to keep the channel concept as known by the end user. Just internally we translate both to `tag` in the ModuleTemlate (https://github.com/kyma-project/lifecycle-manager/issues/1589).

> AC: Add an explicit name attribute (currently it is a label).

We should also state explicitly that the resource name must follow the convention: `<module-name>-<tag>`. `tag` is alpha numeric and MUST NOT include dashes (in case we need to split it again in the future). This will help us simplifying the currently rather complex [template lookup](https://github.com/kyma-project/lifecycle-manager/blob/main/pkg/templatelookup/regular.go#L240-L287) as we can do something like:

```Go
tmplt := &v1beta2.ModuleTemplate{}
err := c.Get(context.Background(), client.ObjectKey{
		Namespace: namespace,
		Name:      fmt.Sprintf("%s-&s", moduleName, moduleTag),
    }, tmplt)
```

Even though we have the resource name convention, name and tag should still be explicit attributes on the spec. An example for a full ModuleTemplate:

```yaml
apiVersion: operator.kyma-project.io/v1beta3
kind: ModuleTemplate
metadata:
  name: template-operator-1.1.0
  namespace: kcp-system
spec:
  name: template-operator
  tag: 1.1.0
  data:
    // ...
  descriptor:
    // ... OCM descriptor for version 1.1.0
  mandatory: false
---
// given the current version for fast is also 1.1.0
apiVersion: operator.kyma-project.io/v1beta3
kind: ModuleTemplate
metadata:
  name: template-operator-fast
  namespace: kcp-system
spec:
  name: template-operator
  tag: fast
  data:
    // ...
  descriptor:
    // ... OCM descriptor for version 1.1.0
  mandatory: false
```

---
