### ISSUE TITLE
[Deletion Modes] Make KLM support `application/x-tar` as access mediaType for `raw-manifest` and `default-cr` resource

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1650]
In order to make [Kyma Module as OCM component](https://github.com/kyma-project/lifecycle-manager/issues/1587) compatible with [ocm-controller](https://github.com/open-component-model/ocm-controller), the `default-cr` and `raw-manifest` resources in Kyma Module should be defined as `application/x-tar` mediaType (as Directory). 

Currently KLM is possible to parsing `raw-manifest` as `application/octet-stream` mediaType (as file), however it is not possible to deploy by ocm-controller.
https://github.com/kyma-project/lifecycle-manager/blob/a0c49436f3d11d03c9a7556ec11c7c9f69d621d9/tests/moduletemplates/moduletemplate_template_operator_v2_fast.yaml#L34-L48

new kyma module ocm component looks like below:
```
resources:
  - access:
      imageReference: europe-docker.pkg.dev/kyma-project/prod/template-operator:1.0.0
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 03a194e1dca2421755cec5ec1e946de744407e6e1ca3b671f715fee939e8d1fb
    name: module-image
    relation: external
    type: ociArtifact
    version: 1.0.0
  - access:
      localReference: sha256:ad76888e8aee1c337eed330443cae54b4f912824e9c17c0f876e48d12f8ad65d
      mediaType: application/x-tar
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: ad76888e8aee1c337eed330443cae54b4f912824e9c17c0f876e48d12f8ad65d
    name: raw-manifest
    relation: local
    type: directory
    version: 1.0.0
  - access:
      localReference: sha256:7b747b3bbc6504c3198c52c764508f0217a39f44cb4ee52ed5f67b3b0fb6df9e
      mediaType: application/x-tar
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 7b747b3bbc6504c3198c52c764508f0217a39f44cb4ee52ed5f67b3b0fb6df9e
    name: default-cr
    relation: local
    type: directory
    version: 1.0.0
  sources: []
  version: 1.0.0
```

## AC
- [x] **Manifest Controller:** KLM is able to deploy `raw-manifest` resource from access mediaType `application/x-tar` and `application/octet-stream` (for backward compatibility)
- [x] (❌ ) **Kyma Controller:** Add that KLM is able to deploy `default-cr` resource from access mediaType `application/x-tar` and `moduletemplate.spec.data` (for backward compatibility) during Manifest CR creation
- [x] Cover with integration test
    - [x] Hint: https://github.com/kyma-project/lifecycle-manager/blob/93a3385641053bfbe04ca6261ba4d14a2af25f2c/tests/integration/controller/manifest/manifest_controller_test.go#L17
- [x] Adapt existing E2E test if necessary

## AC updated:
- [ ] Default CR keep in ModuleTemplate `moduletemplate.spec.data`, so that KLM is able to deploy it directly, but not read from `default-cr` layer.
