### ISSUE TITLE
[Deletion Modes] Implement Logic to Extract and Insert Associated Resources into Manifest CR `associatedResources`

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1651]
### Description

With the issue described in [lifecycle-manager #1582](https://github.com/kyma-project/lifecycle-manager/issues/1582), a new field called associatedResources is added to the `Manifest` Custom Resource. This change requires implementing logic to extract the list of managed resources from the ModuleTemplate and insert it into the `manifest.spec. associatedResources `.

The list of managed resources is an additional layer in the OCM specification. An example of this can be found in the implementation described in [template-operator #200](https://github.com/kyma-project/template-operator/issues/200).

After implementing this logic, the Manifest CR should look like this:

```yaml
[...]
spec:
  install:
    name: raw-manifest
    source:
      [...]
  remote: true
  resource:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Sample
    metadata:
      name: sample-yaml
      namespace: kyma-system
    spec:
      resourceFilePath: ./module-data/yaml
  associatedResources: 
     - serverless.kyma-project.io/v1alpha2/functions
     - operator.kyma-project.io/v1alpha1/serverlesses
  version: 1.1.1
```

### Reasons

- Provide logic to extract managed resources from `ModuleTemplate` OCM Layer
- Fill in `manifest.spec. associatedResources ` list

### Acceptance Criteria

- [x] Kyma Reconciliation Loop:
    - [x] Extract managed resources from OCM layer (`ModuleTemplate`)
    - [x] While creating Manifest CRs insert extracted managed resources into the `manifest.spec. associatedResources `
- [x] Cover newly introduced functions in Unit-Tests
- [x] Cover new functionality of Kyma reconciliation loop in integration test
