### ISSUE TITLE
Mapping module deployment state to ManifestCR state

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1706]
Created on 2024-07-22 by Christoph Schwägerl

## Decision log

| Name               | Description                                          |
| ------------------ | ----------------------                               |
| Title              | Mapping module deployment state to ManifestCR state  |
| Due date           | 2024-07-25                                           |
| Status             | Accepted 2024-07-25                                                |
| Decision type      | Choice                                               |
| Affected decisions | [#899](https://github.com/kyma-project/community/issues/899) (extends) |

## Context

In [#899](https://github.com/kyma-project/community/issues/899) it was decided to separate "Manifest State" from "Module State" with

> *"Manifest State - standing for the overall health of K8S resources that the Module consists of. This state is managed solely by the Kyma Lifecycle Manager, it contains information on whether the K8S manifest was applied correctly and deployment is running or not."*

This decision record aims at defining the exact mapping from the state of the applied K8s resources to the state of the Manifest CR.

## Key Assumptions and Boundary Conditions

- **Boundary Condition B1**: Values for Manifest State are as proposed in [#899](https://github.com/kyma-project/community/issues/899):
  - **Ready** - Manifest was applied correctly and the workload is running
  - **Processing** - Lifecycle Manager waits for the pods to get up/K8S to apply changes
  - **Deleting** - The manifest is under deletion, most likely waiting for some blocking resource removal
  - **Error** - There was an issue that is not able to be resolved automatically and a grace period/number of retries was used
- **Key Assumption A1**: It is assumed that [Deplyoment status](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status) describes the complete list of possible reasons. The [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#deploymentcondition-v1-apps) does not list possible reasons.

## Decision

- If the ManifestCR has a deletion timestamp, `.status.state` is set to `Deleting`.
- If the application of the resources to the SKR returns with error, `.status.state` is set to `Error`.
- If no deployment is found, `.status.state` of ManifestCR is set to `Ready` (temporary solution until the same is implemented for stateful sets).
- If a deployment is found, `.status.state` is derived from the [Deployment status](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status). The mapping of the diffeerent deployment conditions to ManifestCR status is done as proposed in the section below "Deployment status to ManifestCR status Mapping".

## Consequences

Kyma lifecycle manager is updated to compute the ManifestCR status as decided in [Decision](#decision)

## Deployment status to ManifestCR status Mapping

Summary from [Deployment status](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status) (readers of this ADR are still expected to have read the full Deployment status section):

K8s describes the set of possible states of a deployment as [Progressing](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progressing-deployment), [Complete](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#complete-deployment) or [Failed](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment).
In short, it seems that the state is made up from conditions of `type: Progressing` and `type: Available`, where:

> `type: Progressing` with `status: "True"` means that your Deployment is either in the middle of a rollout and it is progressing or that it has successfully completed its progress and the minimum required new replicas are available (see the Reason of the condition for the particulars - in our case reason: NewReplicaSetAvailable means that the Deployment is complete).

> `type: Available` with `status: "True"` means that your Deployment has minimum availability. Minimum availability is dictated by the parameters specified in the deployment strategy.

From this, we may derive the following in terms of ManifestCR status.

```yaml
# Deployment
status:
  conditions:
    - type: Available
      status: True
    - type: Progressing
      status: True
      reason: NewReplicaSetAvailable
# ManifestCR
status:
  state: Ready
```

Deployment is having minimum availability and running on the desired spec version (last rollout complete).

```yaml
# Deployment
status:
  conditions:
    - type: Available
      status: True
    - type: Progressing
      status: True
      reason: [NewReplicaSetCreated, FoundNewReplicaSet, ReplicaSetUpdated]
# ManifestCR
status:
  state: Processing
```

Deployment is having minimum availability in an old version and is being updated to a new desired version.

```yaml
# Deployment
status:
  conditions:
    - type: Available
      status: False
    - type: Progressing
      status: True
      reason: [NewReplicaSetCreated, FoundNewReplicaSet, ReplicaSetUpdated, NewReplicaSetAvailable]
# ManifestCR
status:
  state: Processing
```

Deployment is NOT having minimum availability and is being rolled out. It may be a new deployment or may be in the process of getting more replicas (this may include change to a newer version).

```yaml
# Deployment
status:
  conditions:
    - type: Available
      status: True
    - type: Progressing
      status: False
      reason: [ProgressDeadlineExceeded, ReplicaSetCreateError, <anything not in the list above>]
# ManifestCR
status:
  state: Error
```

Deployment is having minimum availability in an old version, but it failed to rollout the new desired version.

```yaml
# Deployment
status:
  conditions:
    - type: Available
      status: False
    - type: Progressing
      status: False
      reason: [ProgressDeadlineExceeded, ReplicaSetCreateError, <anything not in the list above>]
# ManifestCR
status:
  state: Error
```

Deployment is NOT having minimum availability in an old version and it failed to rollout the new desired version. May have failed to get created initially. May have failed to update to a new version with more replicas.

### Remarks

The examples shown in [Failed Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment) also include the condition `type: ReplicaFailure`. This conditions indicates the error while rolling out new replicas. However, we seems as if it is not necessary to check it explicitly since it will be retried while Progressing within the `progressDeadlineSeconds` (ManifestCR remains in Processing state), and if it has not succeeded within the deadline, Progressing will be set to false with a `ProgressDeadlineExceeded` reason (ManifestCR transitions to Error state).

### State Diagram

States are the states the ManifestCR is in. Notes add the related state of the deployment.

```mermaid
stateDiagram-v2

    [*] --> Processing(Unavailable): New deployment applied
      note right of Processing(Unavailable)
        # Deployment
        status:
          conditions:
            - type: Available, status: False
            - type: Progressing, status: True
              reason: [NewReplicaSetCreated, FoundNewReplicaSet, ReplicaSetUpdated, NewReplicaSetAvailable]
      end note

    Processing(Unavailable) --> Ready: Deployment completed
      note left of Ready
        # Deployment
        status:
          conditions:
            - type: Available, status: True
            - type: Progressing, status: True
              reason: NewReplicaSetAvailable
      end note

    Ready --> Processing(Available): New version applied
      note left of Processing(Available)
        # Deployment
        status:
          conditions:
            - type: Available, status: True
            - type: Progressing, status: True
              reason: [NewReplicaSetCreated, FoundNewReplicaSet, ReplicaSetUpdated]
      end note

    Processing(Available) --> Ready: Deployment completed

    Ready --> Processing(Unavailable): Replicas scaled up (may include new version)

    Processing(Available) --> Error(Available): Failed to complete deployment
    note right of Error(Available)
        # Deployment
        status:
          conditions:
            - type: Available, status: True
            - type: Progressing, status: False
              reason: [ProgressDeadlineExceeded, ReplicaSetCreateError, ...]
    end note

    Processing(Unavailable) --> Error(Unavailable): Failed to complete deployment

    note right of Error(Unavailable)
      # Deployment
      status:
        conditions:
          - type: Available, status: False
          - type: Progressing, status: False
            reason: [ProgressDeadlineExceeded, ReplicaSetCreateError, ...]
      end note
```
