### ISSUE TITLE
[ModuleCatalog] Add `.spec.manager` info to ModuleTemplate

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1840]
### Description

In https://github.com/kyma-project/lifecycle-manager/issues/1681 it has been decided to add explicit information identifying a module's manager to the ModuleTemplate. We need to update the ModuleTemplate to include this information.

The information shall look as follows:

```
spec:
  manager:
    group: <group>
    version: <version>
    kind: <kind>
    namespace: <namespace>
    name: <name>
```

`.spec.manager` is OPTIONAL (for compatibility reasons), but the individual entries are REQUIRED, except Namespace which can be OPTIONAL due to CRDs not being namespaced. It should be checked whether existing K8s types and validations can be re-used.

### Reasons

Enables CLI and dashboard to determine whether a module is installed or not (manual installation case)

### Acceptance Criteria

- [x] re-used K8s types if possible
- [x] `.spec.manager` added to ModuleTemplate
- [x] Added an entry to https://github.com/kyma-project/lifecycle-manager/issues/776 that `.spec.manager` must be added as required in a future major API version
