### ISSUE TITLE
[ModuleCatalog] Add `.spec.info` to ModuleTemplate

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1841]
### Description

In https://github.com/kyma-project/lifecycle-manager/issues/1681 it has been decided to add information about the module to the ModuleTemplate. We need to update the ModuleTemplate to include this information.

The information shall look as follows:

```yaml
spec:
  info:
    repository: <link>
    documentation: <link>
    icons:
    - name: <string>
      link: <link>
```

.spec.info is OPTIONAL (for compatibility reasons), but the individual entries are REQUIRED.

### Reasons

Enables CLI and dashboard to show additional info about the module

### Acceptance Criteria

- [x] `.spec.info` added to ModuleTemplate
- [x] Added an entry to https://github.com/kyma-project/lifecycle-manager/issues/776 that `.spec.info` must be added as required in a future major API version
- [x] Update documentation
