### ISSUE TITLE
[ModuleCatalog] Add `.spec.associatedResources` to ModuleTemplate

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#1843]
### Description

In https://github.com/kyma-project/lifecycle-manager/issues/1681 it has been decided to add info about resources associated to a module to ModuleTemplates. We need to update the ModuleTemplate to include this information.

The information shall look as follows:

```yaml
spec:
  associatedResources:
  - group: networking.istio.io
    version: v1alpha3
    kind: gateways
  - group: networking.istio.io
    version: v1alpha3
    kind: virtualservices
```

.spec.associatedResources is OPTIONAL (for compatibility reasons). The items in an individual entry are REQUIRED. It should be checked whether existing K8s types and validations can be re-used.

### Reasons

Enables CLI and dashboard to show a message about what resources must be cleaned when uninstalling a module.

### Acceptance Criteria

- [ ] re-used K8s types if possible
- [ ] `.spec.associatedResources` added to ModuleTemplate
- [ ] Added an entry to https://github.com/kyma-project/lifecycle-manager/issues/776 that `spec.associatedResources` must be added as required in a future major API version
