### ISSUE TITLE
[ModuleCatalog] Introduce `ModuleReleaseMeta` CRD

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1848]
### Description:
We need to create a new Custom Resource Definition (CRD) named `ModuleReleaseMeta`. However, the name can be challenged if a better alternative is found (e.g., `ChannelAssignment` or similar). For now we drop the feature of introducing specifying Module versions in this CR.

Detailed decision ticket:  https://github.com/kyma-project/lifecycle-manager/issues/1815

### Requirements:
- The `spec` should include:
  - `moduleName`: a non-optional string.
  - `channels`: a list where each item must include the mandatory fields `channel` and `version`.
- The `apiVersion` for the CRD should be `operator.kyma-project.io/v1beta2`.

### Example CRD YAML:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modulereleasemetas.operator.kyma-project.io
spec:
  group: operator.kyma-project.io
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                moduleName:
                  type: string
                  description: "The name of the module"
                  minLength: 1
                channels:
                  type: array
                  description: "List of channels and their corresponding versions"
                  items:
                    type: object
                    properties:
                      channel:
                        type: string
                        description: "The release channel"
                        minLength: 1
                      version:
                        type: string
                        description: "The version for the corresponding channel"
                        minLength: 1
                    required:
                    - channel
                    - version
              required:
                - moduleName
                - channels
  scope: Namespaced
  names:
    plural: modulereleasemetas
    singular: modulereleasemeta
    kind: ModuleReleaseMeta
    shortNames:
      - mrm
```
### Example CR yaml

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleReleaseMeta
metadata:
  name: eventing
spec:
  moduleName: eventing
  channels:
  - channel: regular
    version: 1.0.0
  - channel: fast
    version: 1.1.0
  - channel: experimental
    version: 2.0.0
```

### Acceptance Criteria:
- [x] CRD is created with the above structure (or a modified version if the name is challenged).
- [x] Documentation is added to explain the new CRD and its usage. 
- [x] Ensure validation is present for the channels list (there should be no duplicates, channels only from specific list, same as in Kyma CR) https://github.com/kyma-project/lifecycle-manager/blob/2342670c9be72df6b33c4cd6ce0d12ccbb65b371/api/v1beta2/kyma_types.go#L51-L54
- [x] Ensure validation is present for versions (semver)
