### ISSUE TITLE
[Restricted Markets] Support Docker image localization

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#1858]
### Description

kyma module in different landscape will use it's transfered container images, in order to support unified deployment, ocm community come up with so called localization concept, and implmented this concept using [localization controller](https://ocm.software/docs/controller/architecture/#localization-controller). 

For Kyma image localization, since all image sources are managed by us internally, we will use a simplified version based on the decision mentioned in [ADR](https://github.com/kyma-project/lifecycle-manager/issues/1587)
> To ensure the Kyma Lifecycle Manager (KLM) can replace localized module images during deployment, all required images must be listed in the Module Operator Deployment Kubernetes resource.
> All images must be published and signed in the central image registry: europe-docker.pkg.dev/kyma-project/prod

With those precondition, it allow us make localization possible using simple replace machanism.
1. scan `Deployment` or `StatefulSet` yaml, replace all image with `europe-docker.pkg.dev/kyma-project/prod/[name]:[tag]` to it's related localized image `[localized host]/[name]:[tag]` 
2. Deploy this modified resource.

#### Example

New OCM format
https://github.com/kyma-project/lifecycle-manager/blob/2342670c9be72df6b33c4cd6ce0d12ccbb65b371/tests/moduletemplates/moduletemplate_template_operator_regular_new_ocm.yaml#L33-L43

In target landscape, this image resource will be replaced to:
```
resources:
  - access:
      imageReference: [target host]/template-operator:1.0.0
      type: ociArtifact
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: ociArtifactDigest/v1
      value: 03a194e1dca2421755cec5ec1e946de744407e6e1ca3b671f715fee939e8d1fb
    name: module-image
    relation: external
    type: ociArtifact
    version: 1.0.0
``` 

### Reasons

Support kyma module deployment in other landscapes.

### Dev Notes

The actual images address should be obtained from ocm resources layer in the target hosts.

### Acceptance Criteria

- [ ] KLM is able to deploy localized kyma module from ocm component
- [ ] OCM `ociArtifact` resources may not only one, for certain modules, it may persists several images, KLM need to support the replacement for all images.

### Feature Testing

Integration tests, End-to-End tests

### Attachments

related issue: https://github.com/kyma-project/lifecycle-manager/issues/1867

**Comment by Tomasz-Smelcerz-SAP** [comment]
Currently in the `manifest` CR we're lacking access to the ocm image list. Here's an example spec:

```
spec:
  install:
    name: raw-manifest
    source:
      name: kyma-project.io/module/telemetry
      ref: sha256:<redacted>
      repo: europe-docker.pkg.dev/kyma-project/kyma-modules/component-descriptors
      type: oci-dir
  remote: false
  resource:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      name: default
      namespace: kyma-system
  version: x.yy.zzz
```

Perhaps one solution would be to add another field to the spec: `localized-images` which would be a list containing all the images from the ocm descriptor of type `ociArtifact`
Then we can use the entries from this list to perform the substitution.
