### ISSUE TITLE
Do not cause Error State if Kyma CR specifies no Modules

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/lifecycle-manager#194]
Kyma CR currently causes an error State when its applied without any modules in its specification. This is a problem as the default apply from CLI and SKR mode will not contain any modules. This will result in the default cluster state to be in Error.

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: default
spec:
  channel: stable
  sync:
    enabled: true
  modules:

```

AC:

- [ ] Applying an empty Kyma should not result in an error state
