### ISSUE TITLE
[Module Catalog] Prepare testing playground for Otters and Hasselhoffs

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#2007]
**Description**

In order to implement UI/CLI changes it would be great to have some sort of testing ground for all ModuleCatalog-related changes.

**Acceptance Criteria**
- [x] Basic CRs set up and present on the DEV landscape + can be checked/interacted with
- [x] Template Operator can be a lab rat for this case
  - prepare some dummy fields (fill them with anything) OR improve what is in the Template Operator artifacts
  - one module, two different versions (for different channels)
  - make sure the dummy module is not propagated to stage/prod
- [x] Modulectl released

**Attachements**
Contact people:
- @mrCherry97 (Hasselhoff)
- @kwiatekus (Otters)

**Comment by lindnerby** [comment]
We have created two versions of template-operator on the DEV landscape. with a corresponding `ModuleReleaseMeta` for mapping the version of `0.0.1-catalog-meta` to channel `regular` and the the version of `0.0.2-catalog-meta` to channel `fast`.

To inspect the modules' versions, run in the context of kyma-mps-**dev**:
```
kubectl get moduletemplate -n kcp-system -l operator.kyma-project.io/module-name=template-operator
```

To have a look at channel mappings, run:
```
kubectl get mrm -n kcp-system template-operator -o yaml
```

To install a version of these module on the skr, run against the **skr** kube:
```
kubectl patch kyma default -n kyma-system --type='merge' \
 --patch '{"spec": {"modules": [{"name": "template-operator", "version": "0.0.1-catalog-meta"}]}}'
```

To disable, run:
```
kubectl patch kyma default -n kyma-system --type='json' --patch '[{"op": "remove", "path": "/spec/modules/0"}]'
```

The templates and artifacts where created with the [latest release of modulectl ](https://github.com/kyma-project/modulectl/releases) and these input config files:
```
name: kyma-project.io/module/template-operator
version: 0.0.1-catalog-meta
manifest: https://github.com/kyma-project/template-operator/releases/download/1.0.1/template-operator.yaml
security: sec-scanners-config.yaml
repository: https://github.com/kyma-project/template-operator
documentation: https://github.com/kyma-project/template-operator/blob/main/README.md
defaultCR: https://github.com/kyma-project/template-operator/releases/download/1.0.1/default-sample-cr.yaml
icons:
  - name: module-icon
    link: https://github.com/kyma-project/template-operator/blob/main/docs/assets/logo.png
associatedResources:
  - group: operator.kyma-project.io
    version: v1alpha1
    kind: Managed
manager:
  name: template-operator-controller-manager
  namespace: template-operator-system
  group: apps
  version: v1
  kind: Deployment
```

```
name: kyma-project.io/module/template-operator
version: 0.0.2-catalog-meta
manifest: https://github.com/kyma-project/template-operator/releases/download/1.0.1/template-operator-statefulset.yaml
security: sec-scanners-config.yaml
repository: https://github.com/kyma-project/template-operator
documentation: https://github.com/kyma-project/template-operator/blob/main/README.md
icons:
  - name: module-icon
    link: https://github.com/kyma-project/template-operator/blob/main/docs/assets/logo.png
associatedResources:
  - group: operator.kyma-project.io
    version: v1alpha1
    kind: Managed
manager:
  name: template-operator-controller-manager
  namespace: template-operator-system
  group: apps
  version: v1
  kind: StatefulSet
```
