### ISSUE TITLE
The make test which run unit and integration tests is failing due to `GOSUMDB`

### ISSUE THREAD

**Issue by medmes** [kyma-project/lifecycle-manager#2296]
### Description

When running the make test command in our CI/CD pipeline, the workflow fails with the following error:

```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20250306013145-9f4e0f706b70 requires go >= 1.24.0; switching to go1.24.1
go: download go1.24.1: golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64: verifying module: checksum database disabled by GOSUMDB=off
make: *** [Makefile:167: /home/runner/work/lifecycle-manager/lifecycle-manager/bin/setup-envtest] Error 1

```

**The issue occurs because:**

The setup-envtest tool requires Go 1.24.0 or later.

The Go toolchain attempts to download Go 1.24.1 to satisfy this requirement.

The GOSUMDB=off setting disables the checksum database, preventing Go from verifying the integrity of the downloaded toolchain.

This issue started occurring recently, even though the workflow previously worked with GOSUMDB=off.

### Steps to reproduce

Use the the existing GitHub Actions workflow:
 - test-unit.yml:
 
```
name: TestSuite integration and unit tests

permissions: { }

on:
  pull_request:
    branches:
      - main
      - feat/**

jobs:
  envtest-and-unittest:
    name: "Run 'make test'"
    runs-on: ubuntu-latest
    env:
      GOSUMDB: off
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run 'make test'
        run: |
          make test
```

### Environment Type

Github Actions CI/CD

### Environment Info

- **Workflow File:** .github/workflows/test-unit.yaml
- Go Mod File: go.mod
- Makefile command: make test

- Relevant Dependencies:
 - sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

### Proposal Solution
Remove `GOSUMDB` form the workflow to set it to default or set it to `sum.golang.org`

### Acceptance Criteria
- [x] Drop the `GOSUMDB` env variable
- [x] Do a short investigation
- [ ] If further action is required create a follow-up ticket
