### ISSUE TITLE
[Gardener CM] Check if kustomizeconfig for certmanager works properly

### ISSUE THREAD

**Issue by c-pius** [kyma-project/lifecycle-manager#2349]
### Description

Gardener CM returns errors when there is no Common Name defined. For the webhook cert, we seemed to have introduced it via the config/certmanager/kustomizeconfig.yaml. But at least in the PoC it didn't work and I had to provide it explicitly. We should investigate if this config really works and assigns all fields properly.

**Timebox: 2 days**

### Reasons

Follow-up from https://github.com/kyma-project/lifecycle-manager/issues/2312.

### AC

- [x] understood how kustomizeconfig.yaml works
- [x] understood whether we are using it properly
- [x] created the necessary follow-ups

**Comment by LeelaChacha** [comment]
### Findings
The kustomizeconfig.yaml file is a [transformerconfig](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs). It contains instructions to transform fields in the kustomization output.

1. The nameReference:
```
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
      - kind: Certificate
        group: cert-manager.io
        path: spec/issuerRef/name
```
It is used to associate the `metadata.name` field of the issuer to the `spec.issuerRef.name` field of the Certificate. Since the name of the issuer will be prefixed with `klm-`, the issuerRef of the certificate also needs to be updated. This nameReference tells kustomize to also add the prefix to that field.
