### ISSUE TITLE
[Submission Pipeline] Kustomization Setup in `kyma-modules` Repository

### ISSUE THREAD

**Issue by LeelaChacha** [kyma-project/lifecycle-manager#2381]
### Description

This is the dir structure that we want to have in the `kyma-modules` repo:
```
|-- <module>
    |-- versions
        |-- moduletemplate-<version1>.yaml
        |-- moduletemplate-<version2>.yaml
    |-- module-release-meta.yaml
    |-- kustomization.yaml
    |-- patch-add-dev-channel.yaml
    |-- patch-add-experimental-channel.yaml
|-- dev
    |-- kustomization.yaml
|-- stage
    |-- kustomization.yaml
|-- prod
    |-- kustomization.yaml
```
This will allow us to keep the environments separate. We will have one base kustomization.yaml for each module: 
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - module-release-meta.yaml
  - versions/moduletemplate-1.32.0.yaml
  - versions/moduletemplate-1.34.0.yaml
  - versions/moduletemplate-1.34.0-experimental.yaml
```
All the versions will be listed here along with the module-release-meta.yaml. The MRM will only contain the fast and regular channels:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleReleaseMeta
metadata:
  name: telemetry
  namespace: kcp-system
spec:
  moduleName: telemetry
  channels:
    - channel: regular
      version: 1.32.0
    - channel: fast
      version: 1.34.0
```
The rest of the channels will be introduced through patches, so that we can dynamically add the patches when syncing to dev or stage. Here is an example of the patch:
```
- op: add
  path: /spec/channels/-
  value:
      channel: dev
      version: 1.32.0
```
### `dev/kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../telemetry

patches:
  - path: ../../telemetry/patch-add-dev-channel.yaml
    target:
      kind: ModuleReleaseMeta
      name: telemetry
  - path: ../../telemetry/patch-add-experimental-channel.yaml
    target:
      kind: ModuleReleaseMeta
      name: telemetry
```

 These modules will be referenced by the landscape kustomization.yaml

### Reasons

We need a clean way to separate experimental and dev channels from PROD.

### Acceptance Criteria

- [ ] 3 kustomizations exist for the 3 landscapes
  - [ ] both patches are applied for dev
  - [ ] only experimental patch is applied for stage
  - [ ] no patch is applied for prod
- [ ] path in modulectl-create.sh is adapted with the new dir structure (separate issue?)
  - [ ] When creating the template, it is placed in `versions` dir
  - [ ] template added to the `kustomization.yaml` in the `<module>` dir
- [ ] SREs are contacted to set up argo jobs for all three landscapes

### Dev Notes
1. To load patch from the parent of kustomization.yaml, the option `--load-restrictor LoadRestrictionsNone` must be provided to kustomize, for local testing and later for argo jobs (the possibility of this option in the argo environment is confirmed by SREs).
2. The patches can also be empty. So we can have the same file structure for all modules regardless of the presence of dev or experimental channels.

### Attachments

[PoC Structure](https://github.tools.sap/kyma/kyma-modules/tree/poc/kustomize-for-new-submission-pipeline)
