### ISSUE TITLE
[Submission Pipeline] Support Additional Channel-Version Mapping Config in `module-manifests` Repository

### ISSUE THREAD

**Issue by LeelaChacha** [kyma-project/lifecycle-manager#2387]
### Description

The new submission pipeline has no information on the module version it is processing. Therefore, it is not possible to sync the generated module template into the KCPs of different landscapes, e.g. `dev` or `experimental` module versions should be limited to `dev` and `stage` landscapes.

To provide the submission pipeline with the information on what channel a version will be mapped to, we need an additional mapping config in the `module-manifests` repo.

This shall be called `channel-config.yaml` and placed in the module directory. This will be an optional input to the pipeline, i.e. the moduletemplate should still be created if no changes in the `channel-config.yaml` file are made. However, it should also be possible to trigger the pipeline by only changing `channel-config.yaml` and not `module-config.yaml` for a module. In other words, it is a sufficient but not necessary condition.
The structure of the `channel-config.yaml` is fixed and same as the spec of a ModuleReleaseMeta. :
```yaml
 channels:
    - channel: experimental
      version: <version1>
    - channel: regular
      version: <version2>
    - channel: fast
      version: <version3>
```
This file will provide the information about the modality of version. E.g., if the pipeline is creating a moduletemplate for <version1>, it will have the information that this version is a `experimental` version according to the `channel-config.yaml`. This will help it to put it in the right landscapes - only  in DEV and STAGE landscape and not PROD.
**Note:** It is not necessary that all channels are mentioned in the `channel-config.yaml`. Furthermore, the version of the module that the pipeline is processing might also not be mentioned in `channel-config.yaml`, then the generated module template should not be synced in any landscapes.

The pipeline currently only produces module templates without mentioning them in a `kustomization.yaml`; therefore, these are not synced to the KCPs. This should stay like that. Entries in the kustomize setup will only be made when changes in `channel-config.yaml` are made.

#### Kustomize Setup:
This is how the kustomize setup should look like:
```
|-- <module>
    |-- moduletemplate-<module>-<version1>.yaml
    |-- moduletemplate-<module>-<version2>.yaml
    |--dev
        |-- module-release-meta.yaml
    |-- stage
        |-- module-release-meta.yaml
    |-- prod
        |-- module-release-meta.yaml
|-- kustomizations
    |--dev
        |-- kustomization.yaml
    |-- stage
        |-- kustomization.yaml
    |-- prod
        |-- kustomization.yaml
```
We already have the moduletemplates created by the currently implemented steps. However, three different kustomizations shall be created, each in its own folder. These will contain references to the module templates and module-release-meta suitable for the respective environment. This is how we will make sure the dev and experimental modules are never synced in  PROD landscape.

#### New Step in Pipeline:
A new step in the pipeline shall handle the `channel-config.yaml`. The script shall do two things:
1. Ensure the module template for the versions mapped to a channel is referenced in the `kustomization.yaml` of the landscape where that channel is allowed. A template might be referenced in multiple landscapes, if allowed. Here is a table of channels and the landscapes that they are allowed in:

| Channel | Allowed in Landscape |
|--------|--------|
| dev | DEV |
| experimental | DEV, STAGE |
| fast | DEV, STAGE, PROD |
| regular | DEV, STAGE, PROD |

2. Ensure the channel-version mapping is set in module-release-meta.yaml. There shall be 3 MRMs, one for each landscape. These shall be statically referenced in the `kustomization.yaml` of their respective landscapes. It is important that each mrm is updated with the channel-version mapping. Furthermore, there are limitations on what channels are allowed for which MRM. Only allowed channels should be mentioned in the MRM. Here is the overview:

| Channel | Allowed in MRM |
|--------|--------|
| dev | <module>/dev/module-release-meta.yaml |
| experimental | .../dev/...yaml, .../stage/...yaml |
| fast | .../dev/...yaml, .../stage/...yaml, .../prod/...yaml |
| regular | .../dev/...yaml, .../stage/...yaml, .../prod/...yaml |

### Acceptance Criteria

- [x] Triggers for the submission pipeline are adjusted, such that it also triggers when changes are made in `channel-config.yaml`
  - [x] `channel-config.yaml` should not trigger the old submission pipeline
- [x] A new step for handling `channel-config.yaml` is created. 
  - [x] only triggered when `channel-config.yaml` is changed in PR.
  - [x] It is checked that all the mapped versions already exists in `kyma-modules` repo; fail the pipeline if otherwise.
  - [x] ensured that reference to all versions in the `channel-config.yaml` exist in the landscape `kustomization.yaml` for the mapped channel, create if not
    - previously existing resources should not be deleted in this step
  - [x] ensured that mapping exists in the correct MRMs in the module directory, create if not
    - [x] perform a check against the ModuleReleaseMeta (`kyma-modules` repository) to see if the module was downgraded, in such a case the submission should be rejected

Follow-up Issues: Documentation, Contacting SREs to set up Argocd jobs on the kustomizations

### Dev Notes:
This is how the files could look like:
 - `kustomizations/dev/kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../telemetry/dev/module-release-meta.yaml
  - ../../telemetry/moduletemplate-telemetry-1.32.0.yaml
  - ../../telemetry/moduletemplate-telemetry-1.34.0.yaml
  - ../../telemetry/moduletemplate-telemetry-1.34.0-experimental.yaml
```
 - `kustomizations/prod/kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../telemetry/prod/module-release-meta.yaml
  - ../../telemetry/moduletemplate-telemetry-1.32.0.yaml
  - ../../telemetry/moduletemplate-telemetry-1.34.0.yaml
```
 - `telemetry/dev/module-release-meta.yaml`:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleReleaseMeta
metadata:
  name: telemetry
  namespace: kcp-system
spec:
  moduleName: telemetry
  channels:
    - channel: dev
      version: 1.32.0
    - channel: experimental
      version: 1.34.0-experimental
    - channel: regular
      version: 1.32.0
    - channel: fast
      version: 1.34.0
```
 - `telemetry/prod/module-release-meta.yaml`:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleReleaseMeta
metadata:
  name: telemetry
  namespace: kcp-system
spec:
  moduleName: telemetry
  channels:
    - channel: regular
      version: 1.32.0
    - channel: fast
      version: 1.34.0
```

**Comment by LeelaChacha** [comment]
Deletion from the kustomization.yaml will be handled in https://github.com/kyma-project/test-infra/issues/12673

**Comment by ruanxin** [comment]
> This will be called `mapping-config.yaml` and placed in the same directory as the `module-config.yaml`.

- Maybe name it `channel-config.yaml`, mapping doesn't express the purpose.

- I would choose the same structure defined in MRM for this `channel-config.yaml`, so we can have some logic to deal with this mapping both for config and MRM

```
  channels:
    - channel: dev
      version: 1.32.0
    - channel: experimental
      version: 1.34.0-experimental
    - channel: regular
      version: 1.32.0
    - channel: fast
      version: 1.34.0
```

- The new configuration file should not in the same directory as `module-config.yaml`, right? `module-config.yaml` is per version based and located under the version folder, and this new one better put under module root folder, like below:
```
|-- <module>
    |-- 1.0.0
        |-- module-config.yaml
    |-- 1.1.0
    |-- module-config.yaml
    |-- channel-config.yaml
```
