### ISSUE TITLE
Migrate kustomize setup to kustomize v5

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#391]
**Description**
The KLM is currently setup with kustomize v4. `5.0.0` was [released](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0) which introduces a lot of breaking changes. To stick to the latest changes, features and fixes we should think of upgrading to latest kustomize version.

Example breaking changes which at least affect this project:
- Dropped `patchesStrategicMerge`. Please use [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) instead
- Dropped `patchesJson6902`. Please use [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) instead
- Dropped `vars`. Please use [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) instead.

Unfortunately, the new `patches` do not work as `patchesJson6902` did before. I.e. in kubebuilder v4 the render order of the kustomizations have been the following:
1. patches
2. global patches (i.e. `namespace: kcp-system`)
3. json patches

The following kustomization:
```yaml
namespace: GLOBAL-system

patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: OLD-namespace
    target:
      group: networking.istio.io
      version: v1beta1
      kind: Gateway
      name: watcher-gateway

patchesJson6902:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: JSON-namespace
    target:
      group: networking.istio.io
      version: v1beta1
      kind: Gateway
      name: watcher-gateway
```

Would have the following output:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klm-watcher-serving-cert
  namespace: JSON-system
spec:
  <...>
```

Since JSON patches have been deprecated, the render order is the following:
1. patches
2. global patches (i.e. `namespace: kcp-system`)

Means the kustomization above, would render to the following with v5 using only `patches`:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klm-watcher-serving-cert
  namespace: GLOBAL-system
spec:
  <...>
```

This means, it is no longer possible to have a namespace set and applying to all resources and overwriting it on single specific resources to a different value. Means we need a patch for each resources to set its namespace specifically, which results in at least one patch for each resource. &rarr; Way more patches and kustomization we need to take care of (huge effort atm).

 Maybe there will be a solution given by kustomize, since we will not the only one run into this problem.

[Here ](https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4/config) is the official example form kustomize, maybe they update it with a corresponding example.

ACs:
- [ ] Adapt all patches to work with kustomize 5.x.x (latest)
    - [ ] Run local watcher setup (https://github.com/kyma-project/lifecycle-manager/blob/646e049c3ce5b5a5d1fa3f24549662994f9a017d/docs/developer/watcher-local-test.md#L1) 
 - [ ] Test if Management-Plane-Config renders correctly
 - [ ] Align with SRE, since they still use v4 -> need to upgrade to v5
