### ISSUE TITLE
Kyma state set to `Ready` even if Conditions are not met

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#432]
**Description:**
The Kyma state determines the overall state of the Kyma CR. Means if it is set to `Ready`, all conditions should be ready as well. Unfortunately, it will already be set to true if the SKRWebhookIsReady condition is set to `True`.

```
status:
  activeChannel: regular
  conditions:
  - lastTransitionTime: "2023-02-28T08:09:59Z"
    message: skrwebhook is synchronized
    observedGeneration: 1
    reason: SKRWebhookIsReady
    status: "True"
    type: Ready
  lastOperation:
    lastUpdateTime: "2023-02-28T08:09:59Z"
    operation: kyma is ready
  modules:
  - channel: regular
    fqdn: kyma-project.io/template-operator
    manifest:
      apiVersion: operator.kyma-project.io/v1beta1
      kind: Manifest
      metadata:
        generation: 1
        name: kyma-sample-template-operator-3685142144
        namespace: kcp-system
    name: template-operator
    state: Processing
    template:
      apiVersion: operator.kyma-project.io/v1beta1
      kind: ModuleTemplate
      metadata:
        generation: 1
        name: moduletemplate-template-operator
        namespace: kcp-system
    version: 1.2.3
  state: Ready
```

**Steps to reproduce:**
1. Deploy KLM locally on a k3d cluster, create KymaCR and correpsonding secret; You can use local setup guide: https://github.com/kyma-project/lifecycle-manager/blob/d94177b34bf404ad77f2d905689b59b5a98fa6e9/docs/developer/local-test-setup.md
2. Check KymaCR while module is still in processing (to easify this, you can change the image the template operator uses to one which does not exist -> ImagePullBackoff; module will be in Processing for a while)

**ACs:**
- [ ] Kyma State should be set to `Ready` if, and only if,  all conditions are met
