### ISSUE TITLE
Support remote module templates

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/lifecycle-manager#457]
Provide a way to install a module template that is not available in the control plane but is present in the target cluster.

**Reason**
Teams want to verify that their module template can be applied safely on real environment before they make it available to thousands of customers. Such test case should not require access to Kyma Control Plane (to apply module template there) as we want to keep number of people (teams) having write access to KCP limited. 

**Sample CR**
Here is a proposal how it could look like, but feel free to come with own ideas:
```
apiVersion: operator.kyma-project.io/v1beta1
kind: Kyma
metadata:
  name: default-kyma
  namespace: kyma-system
spec:
  channel: regular
  modules:
  - name: {moduleName}
    template: {namespace}/{name}    # reference to moduletemplate resource in my cluster
    customResourcePolicy: CreateAndDelete
```
