### ISSUE TITLE
Provide a reference to the module CR after enabling module

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#506]
**Description:**
After enabling the module it is unclear which resources were created and can be used to configure that module. To track it the user would need to go to the ModuleTemplate and check what the apiVersion is and what kind of a resource was created and then ask for a specific resource.

This can be simplified by providing a direct reference to the CR that was created in the Status field of the Kyma CR, i.e. for Keda it would be something like this:
```
modules:
    - name: keda
      state: Ready
      channel: alpha 
      ...
      resource:
        apiVersion: operator.kyma-project.io/v1beta1
        kind: Keda
        metadata:
          name: keda-sample
          namespace: kyma-system
```

**Acceptance Criteria:**
- [ ] Kyma CR contains a direct reference to the module CR that was created by enabling a module
