### ISSUE TITLE
Make config layer optional

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#514]
At the moment, lifecycle manager expected a config layer exists in ModuleTemplate component descriptor. However, some modules may not require a config.yaml file to function properly. In this case, the lifecycle manager should be able to handle the ModuleTemplate without the config layer.

```
apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
  descriptor:
    component:
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: 0.0.1-6cd5086

```

AC:
- [x] Make sure kyma CLI can deal with module operator without config.yaml during module creation.
- [x] Update the template operator document to indicate that the config.yaml file is not mandatory for creating modules.
- [x] Make sure Lifecycle manager can handle no config layer ModuleTemplate correctly.
