### ISSUE TITLE
Target (SKR) objects name/namespace configuration overrides.

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#60]
This is needed for the Load Testing purposes, but it looks like a general feature that the Users would like to have.

For the Load Testing we have:
10 000 of Kymas with 20 components each, every component handled by the Manifest CR.
This results in 200 000 of Manifest objects.
Every Manifest CR causes an installation of  some Helm chart in the target cluster.
Let's assume this Helm chart just contains a custom CR, a single k8s object.
200 000 Manifests means then 200 000 custom CRs installed in the target cluster(s)
How do we control names/namespaces of these objects?

_Note: The number of target objects deployed in the single target cluster of course depends on how many target clusters we have. For 4 target clusters we have 200 000 / 4 => 50 000 objects. But this doesn't matter for the discussed feature._

I am putting some proposals below. Feel free to extend it.

1.  A single namespace for all CRs

    In that scenario every object is installed in the same namespace in the target cluster. Then the names of these objects must be different to avoid collisions. This brings two questions:
    - How and where do we generate names for these objects? Of course Helm chart could just "randomize" the name, but it's not the reality of how Helm charts are written. We should expect a fixed name in the chart, with an ability to override it. Can we define such an override in the Kyma object?
    - How do we configure custom state checking function for every object (different names)? We somehow need to know the name upfront.
    
3. Different namespaces

     - 2.1. Different target namespace per Kyma object

        This is the setup we used previously. For every Kyma  object in the control-plane we've created a separate namespace in the target (SKR) cluster. All the custom CRs related to a single Kyma object and installed in the target cluster, ended up in the same namespace. So for 10 000 Kymas we've had 10 000 namespaces. It would be nice to be able to configure this namespace's name somehow - we've just use the name of the Kyma object by customizing the Manifest Operator code.
         Because we have different namespaces, names of components (20 of them) must be unique inside the namespace, but can be otherwise fixed i.e. `component 1` can always be named like "component1" in all namespaces - no collisions.

    - 2.2. Different target namespace for every single CR

       Extreme case, but this setup most closely corresponds to the "real" SKR. After all, in the real installation, most of the Kyma components are installed in their separate namespaces. For the 200 000 Manifests and related 200 000 custom CRs we need 200 000 namespaces in the target cluster(s). As a consequence all the components may even have the same fixed name, like "load-test-component", and there are no collisions because every one is deployed in a different namespace.

The question is:
- Which of the above  can we setup at this moment with just the code we have?
- Which of the above we consider a valid and useful scenario that can be easily implemented even during the POC?

**Comment by jakobmoellersap** [comment]
Towards 1:

> How and where do we generate names for these objects? Of course Helm chart could just "randomize" the name, but it's not the reality of how Helm charts are written. We should expect a fixed name in the chart, with an ability to override it. Can we define such an override in the Kyma object?

The object names are derived from the helm chart, so when you install them they will use the names from the chart. If you want to override those, we could apply custom settings into the helm installation, but in the current state of the code, there is no way to override this in the Kyma Object, this would only be possible for the template. If we want this, then the Kyma Object will need chart overrides, but it will be very hard to validate those properly. I think in this case we should not allow a generic override since it can make or break a deployment. Instead all overridable flags should be exposed in the CRD of the module and then use this for a setting override.

> How do we configure custom state checking function for every object (different names)? We somehow need to know the name upfront.

This is possible today, please look a the sample below taken from https://github.com/kyma-project/kyma-operator/blob/main/operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample
  namespace: default
spec:
  channel: stable
  components:
    - name: manifest
      channel: stable
      settings:
        - apiVersion: operator.kyma-project.io/v1alpha1
          kind: Kyma
          name: kyma-sample
          namespace: default
          state: "Processing"
```
As you can see, you can customize almost everything for the state check.

Towards 2:
2.1 => We currently cannot override the synced namespace based on the Kyma Installation but I would consider this a valid extension of the Kyma CR. I would suggesting implementing a remoteInstallationNamespace for this and the manifest-operator that is generically overriding CR installation locations.

2.2 => I think the real scenario will always correspond to one "kyma-system" namespace, but this is debatable of course. I would say this is a bit too far out there though, so I think we should stick to the other approaches.



> Which of the above can we setup at this moment with just the code we have?

2.1 can be used as is without configuring the namespace. Alternatively you can use 1 with the helm chart ensuring uniqueness. Everything else needs additional implementation

> Which of the above we consider a valid and useful scenario that can be easily implemented even during the POC?

Very valid question. For me personally I think the target installation in the end will always be the same, realistically the components would all install into separate namespaces and we will never have a case of multiple kyma installations in multiple namespaces. So for me none of the above is "necessary" for a true POC. However to make the load test work I think we should stick to the easiest implementation. For me this would be 1, since almost all of this is already there (except the override which we can work around).

Let me know what you think :)

**Comment by ruanxin** [comment]
I agreed with @jakobmoellersap suggestion, go for the easiest implementation, and also highlight in the realistic situation, even all component would install into separate namespaces, we don't have the scenario install kyma into different namespace.

Another aspect, please check this Scalability thresholds concern provided in k8s community:
https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md#kubernetes-thresholds
The number of total namespace is also a scalability dimension, in theory, there is no limit of namespace can be created, but in practice, 10000 can hit the performance according to the above article, so in our load test, I don't think it's a good idea introduce this indicator which can be a potentially scalability issue.

**Comment by Tomasz-Smelcerz-SAP** [comment]
@jakobmoellersap 
You wrote that currently we can implement:
`2.1 can be used as is without configuring the namespace. Alternatively you can use 1 with the helm chart ensuring uniqueness. Everything else needs additional implementation`

I agree with you and @ruanxin that the simplest approach is probably enough for us for the POC.

Just to be sure I understood it correctly:

- `2.1 can be used as is without configuring the namespace` It means that although I can't configure the target namespace's name, some unique namespace will be created for every Kyma CR automatically in the target cluster. The name of this namespace - I assume - is it the same as the namespace of the Kyma object in the control plane?

This statement I don't quite understand :

- `Alternatively you can use 1 with the helm chart ensuring uniqueness` - Is there some working example of how can I achieve that? To configure readiness check function properly, I need to know exactly the name/namespace of the target object before it's created. This is because the readiness function and target object attributes are configured in the Kyma object Spec. The Helm chart author must now find a way to generate a unique name that is at the same time 100% predictable - without any external overrides. Any hint here?

**Comment by pbochynski** [comment]
In the real world, such a problem would not exist as we do not allow installing multiple instances of the same component in a single cluster. For load tests, it is an issue as you simulate thousands of clusters with one. 
Simple solution is to use settings in Kyma resource directly. Put in your chart some value like deploymentName and set override in the component CR. Example:

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample-1
  namespace: default
spec:
  channel: stable
  components:
    - name: component1
      channel: stable
      customStates:
        - apiVersion: component.kyma-project.io/v1alpha1
          kind: Manifest
          metadata:
            name: sample-1-component-1
          spec: 
            deploymentName: sample-1-component-1
    - name: component2
      channel: stable
      customStates:
        - apiVersion: component.kyma-project.io/v1alpha1
          kind: Manifest
          metadata:
            name: sample-1-component-2
          spec: 
            deploymentName: sample-1-component-2
---
apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  name: kyma-sample-2
  namespace: default
spec:
  channel: stable
  components:
    - name: component1
      channel: stable
      customStates:
        - apiVersion: component.kyma-project.io/v1alpha1
          kind: Manifest
          metadata:
            name: sample-2-component-1
          spec: 
            deploymentName: sample-2-component-1
    - name: component2
      channel: stable
      customStates:
        - apiVersion: component.kyma-project.io/v1alpha1
          kind: Manifest
          metadata:
            name: sample-2-component-2
          spec: 
            deploymentName: sample-2-component-2
```
