### ISSUE TITLE
Invalid `status.conditions` for a remote Kyma

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#618]
**Description**

During synchronization of a Kyma CR the Module Catalog (ModuleTemplate CRs) is synced correctly.
The Kyma object with an empty module list goes immediately to a `ready` state, and it's synced to the SKR.
The `status.conditions[]` in the SKR copy are wrong though.
Conditions for `Modules` and `ModuleCatalog` are set to "Ready == False" and the message indicates an error has occured. This is different from the values in the original Kyma (the control-plane Kyma CR), which reports all conditions as "Ready == True"

**Expected result**

Conditions for `Modules` and `ModuleCatalog` are correct

**Actual result**
```
  spec:
    channel: regular
  status:
    activeChannel: regular
    conditions:
    - lastTransitionTime: "2023-05-19T07:24:42Z"
      message: not all modules are in ready state
      observedGeneration: 1
      reason: Ready
      status: "False"
      type: Modules
    - lastTransitionTime: "2023-05-19T07:24:42Z"
      message: module catalog is out of sync and needs to be resynchronized
      observedGeneration: 1
      reason: Ready
      status: "False"
      type: ModuleCatalog
    - lastTransitionTime: "2023-05-19T07:24:42Z"
      message: skrwebhook is out of sync and needs to be resynchronized
      observedGeneration: 1
      reason: Ready
      status: "False"
      type: SKRWebhook
    lastOperation:
      lastUpdateTime: "2023-05-19T07:24:42Z"
      operation: kyma is ready
    state: Ready
```
**Steps to reproduce**

Follow the [developer tutorial](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/local-test-setup.md) for local testing.
Create a Kyma with an empty module list and observe it's `status.conditions`

**Troubleshooting**
n/a
