### ISSUE TITLE
Deletion of a failing module keeps listing the module entry in the status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/lifecycle-manager#629]
**Description**
I tried to add a custom module which did not work out. When removing the module, the status of the module stayed and was still displayed in the kyma dashboard.

**Steps to reproduce**

I used a remote cluster setup of the lifecycle-manager using a custom moduletemplate taken from here (with adjusted namespace): https://github.com/kyma-project/telemetry-manager/releases/tag/0.2.0

I added a module entry for the template in the Kyma resource:

```
spec:
 channel: regular
 modules:
 - channel: fast
  name: telemetry
```
It was failing as I did not specify:   `remoteModuleTemplateRef: telemetry`

The error was like that on the kyma resource:
```
 modules:
 - channel: fast
  message: 'no templates were found: in channel fast for module kyma-system/moduletemplate-telemetry'
  name: telemetry
  state: Error
 state: Error
```

After removing the entry from the modules section, the status stayed like that. As the kyma dashboard list view is based on that, it confused me a lot.

**Expected result**
When I remove a module (even in an error state), it is fully removed, also from the status

**Actual result**
It is still present in the status and will make the dashboard display wrong data
