### ISSUE TITLE
Manifest for componentNameMapping: `sha256-digest` fails to install

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#650]
**Description**

The `sha256-digest` component name mapping allows to [use public docker registry for hosting OCM artifacts](https://github.com/kyma-project/lifecycle-manager/issues/364).
The support for it, once working, is broken now.
Tested with the latest `template-operator` and latest-build CLI command:

`kyma alpha create module -v --version v0.0.17 --registry registry-1.docker.io/{USERNAME} --name-mapping=sha256-digest --credentials={TOPSECRET}`

**Expected result**

The module installs properly and the corresponding manifest is in the `Ready` state.

**Actual result**

The manifest is in an error state withe the following status entry:
```
    lastOperation:
      lastUpdateTime: "2023-06-01T06:51:31Z"
      operation: 'Get "https://OCIRegistry:/v2/": dial tcp: lookup OCIRegistry on
        10.43.0.10:53: no such host'
    state: Error
```

**Steps to reproduce**

- Use latest CLI build
- setup your test cluster
- Checkout the template operator, cd to the directory.
- create/push the module to the docker hub using provided `kyma alpha create` command
- observe `template.yaml` created in the project directory
- create moduletemplate from the `template.yaml`
- create sample empty Kyma object
- add the `template-operator` module to sample Kyma object

**Troubleshooting**
n/a
