### ISSUE TITLE
Module CRD is being installed in only one api version

### ISSUE THREAD

**Issue by barchw** [kyma-project/lifecycle-manager#652]
**Description**
When installing Istio module with the following module template deployed on Dev landscape SKR Istio CRD is installed in `v1alpha2` version only.

**Actual result**
Istio CRD is installed in `v1alpha1` and `v1alpha2` api versions.

**Steps to reproduce**
1. Create module template:
```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: moduletemplate-istio
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/module-name": "istio"
spec:
  channel: alpha
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Istio
    metadata:
      name: default
      labels:
        app.kubernetes.io/name: default
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/istio
      provider: internal
      repositoryContexts:
      - baseUrl: europe-docker.pkg.dev/kyma-project/dev/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.0.1-PR-156
      - access:
          digest: sha256:8c0a0edf373e6e1c67ea4525d903982614da59a75cb5b0e248f3b07289166163
          type: localOciBlob
        name: raw-manifest
        relation: local
        type: yaml
        version: v0.0.1-PR-156
      sources:
      - access:
          commit: d77c52391eef32300e5fa8d6210ab5bf6a324a99
          repoUrl: github.com/kyma-project/istio
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        name: module-sources
        type: git
        version: v0.0.1-PR-156
      version: v0.0.1-PR-156
    meta:
      schemaVersion: v2
```
2. Enable Istio in Kyma CR
```yaml
- channel: alpha
    customResourcePolicy: CreateAndDelete
    name: istio
    remoteModuleTemplateRef: moduletemplate-istio
```

**Troubleshooting**
Issue seems not to happen on Kyma installation with local lifecycle-manager(`europe-docker.pkg.dev/kyma-project/prod/lifecycle-manager:latest`) 

**Related links**
- Istio CRD - https://github.com/kyma-project/istio/blob/8aa6f80a2851b57867e037f999b27831436ea1cc/config/crd/bases/operator.kyma-project.io_istios.yaml
- Commit from which the ModuleTemplate comes - https://github.com/kyma-project/istio/tree/8aa6f80a2851b57867e037f999b27831436ea1cc
