### ISSUE TITLE
Error happens when trying to install module that has the module CRD already installed

### ISSUE THREAD

**Issue by barchw** [kyma-project/lifecycle-manager#653]
**Description**
When trying to install Istio module on cluster that already has Kyma installed the installation fails as lifecycle manager cannot apply the CRD

**Expected result**
The CRD applies successfully and Istio module installs

**Actual result**
CRD apply fails with the following error in Manifest CR:
```yaml
operation: |
      failed to install raw manifest CRDs: Apply failed with 2 conflicts: conflicts with "kubectl-client-side-apply" using apiextensions.k8s.io/v1:
      - .metadata.annotations.controller-gen.kubebuilder.io/version
      conflicts with "reconciler" using apiextensions.k8s.io/v1:
      - .spec.versions
  state: Error
``` 

**Steps to reproduce**
1. Deploy Kyma on the cluster
2. Deploy Istio ModuleTemplate to the cluster:
```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: moduletemplate-istio
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/module-name": "istio"
spec:
  channel: alpha
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Istio
    metadata:
      name: default
      labels:
        app.kubernetes.io/name: default
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/istio
      provider: internal
      repositoryContexts:
      - baseUrl: europe-docker.pkg.dev/kyma-project/dev/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.0.1-PR-156
      - access:
          digest: sha256:8c0a0edf373e6e1c67ea4525d903982614da59a75cb5b0e248f3b07289166163
          type: localOciBlob
        name: raw-manifest
        relation: local
        type: yaml
        version: v0.0.1-PR-156
      sources:
      - access:
          commit: d77c52391eef32300e5fa8d6210ab5bf6a324a99
          repoUrl: github.com/kyma-project/istio
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        name: module-sources
        type: git
        version: v0.0.1-PR-156
      version: v0.0.1-PR-156
    meta:
      schemaVersion: v2
```
3. Enable Istio module in Kyma:
```yaml
- channel: alpha
    customResourcePolicy: CreateAndDelete
    name: istio
    remoteModuleTemplateRef: moduletemplate-istio
```
**Troubleshooting**
The error seems to be caused by server side apply conflict caused by the manager of the resource being `reconciler`
