### ISSUE TITLE
When telemetry resource is in Warning state then kyma resource changes to Processing state

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/lifecycle-manager#851]
**Description**
When `telemetry` CR is in warning state we see that `kyma` resource changes to `processing` state which is wrong. `Kyma` resource should also show `warning` state.

**Expected result**

`Kyma` resource should be in `Warning` if one of the moudule CR is in `warning` state.

**Actual result**

`kyma` resource is in state `Warning`

**Steps to reproduce**
1. Enable telemetry module
2. Deploy following pipeline
```
kubectl apply -f https://raw.githubusercontent.com/kyma-project/telemetry-manager/main/config/samples/telemetry_v1alpha1_logpipeline_http.yaml
```

**Troubleshooting**

Checking the manifest CR shows following state
```
    message: installation is ready and resources can be used
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Installation
  lastOperation:
    lastUpdateTime: "2023-09-06T09:48:05Z"
    operation: 'waiting for resources to become ready: '
  state: Processing
```
