### ISSUE TITLE
Module state is not propagated correctly to Kyma CR

### ISSUE THREAD

**Issue by shorim** [kyma-project/lifecycle-manager#868]
**Description**
After the changes done [here](https://github.com/kyma-project/telemetry-manager/pull/405), if the user attempts to delete the Telemetry module while some custom resources related to Telemetry still exist in the cluster, the module deletion is blocked and the state of the Telemetry module will change to `Warning` . However, the Kyma CR shows that the Telemetry module is in `Deleting` state instead of the actual `Warning` state.

Also, the `Processing` state was removed [here](https://github.com/kyma-project/telemetry-manager/pull/333) and initially the Telemetry module state is empty. However, the Kyma CR shows that the Telemetry module is in `Processing` state.

**Expected result**
When Telemetry module is in `Warning` state, it is expected that the Telemetry state in Kyma CR is also `Warning`
```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Warning
```

When the state of the Telemetry module is empty, it is expected that the Telemetry state in Kyma CR is also empty
```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: ""
```
**Actual result**
When Telemetry module is in `Warning` state, the Telemetry state in Kyma CR is incorrectly set as `Deleting`
```
kubectl get telemetry -n kyma-system
NAME      GENERATION   AGE   STATE
default   3            47m   Warning
```

```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Deleting
```

When the state of the Telemetry module is empty, the Telemetry state in Kyma CR is incorrectly set as `Processing`
```
kubectl get telemetry -n kyma-system default
NAME      GENERATION   AGE   STATE
default   1            16s
```

```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Processing
```

**Steps to reproduce**
For reproducing that the `Warning` state of Telemetry module is not propagated to Kyma CR:

1. kyma provision k3d
2. kyma alpha deploy
3. kubectl apply -f moduletemplate.yaml
4. kyma alpha enable module telemetry -c fast
5. Create a sample LogPipeline: kubectl apply -f https://raw.githubusercontent.com/kyma-project/telemetry-manager/main/config/samples/telemetry_v1alpha1_logpipeline.yaml
6. kyma alpha disable module telemetry
7. Check Telemetry state in Telemetry CR (it will be `Warning`):  kubectl get telemetry -n kyma-system
8. Check Telemetry state in Kyma CR (it will be `Deleting`): kubectl get kyma -n kyma-system default-kyma -o yaml

For reproducing that the empty state of Telemetry module is not propagated to Kyma CR:
1. kyma provision k3d
2. kyma alpha deploy
3. kubectl apply -f moduletemplate.yaml
4. kyma alpha enable module telemetry -c fast
5. Initially before the module is ready, you will observe that Telemetry state in Telemetry CR is empty while Telemetry state in Kyma CR is `Processing`

**NOTE**: The changes [here](https://github.com/kyma-project/telemetry-manager/pull/405) are not released yet. So, you can use the below moduletemplate.yaml for debugging:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: telemetry-fast
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "telemetry"
  annotations:
    "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/telemetry-manager/user/README"
    "operator.kyma-project.io/is-cluster-scoped": "false" 
spec:
  channel: fast
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      labels:
        app.kubernetes.io/name: telemetry
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: telemetry-operator
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/created-by: telemetry-operator
      name: default
  descriptor:
    component:
      componentReferences: []
      labels:
      - name: security.kyma-project.io/scan
        value: enabled
        version: v1
      name: kyma-project.io/module/telemetry
      provider: internal
      repositoryContexts:
      - baseUrl: europe-west3-docker.pkg.dev/sap-kyma-huskies-dev/telemetry-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:226f793665a6c87a30099119bb170694370df21baca4c51f3b44f02a12e5b235
          type: localOciBlob
        name: raw-manifest
        relation: local
        type: yaml
        version: 1.0.0
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:v20230911-69866791
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: telemetry-manager
        relation: external
        type: ociImage
        version: v20230911-69866791
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.83.0-da21e9f9
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: otel-collector
        relation: external
        type: ociImage
        version: 0.83.0-da21e9f9
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.1.8-da21e9f9
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: fluent-bit
        relation: external
        type: ociImage
        version: 2.1.8-da21e9f9
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20230824-2d68935f
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: directory-size-exporter
        relation: external
        type: ociImage
        version: v20230824-2d68935f
      sources:
      - access:
          commit: 74293a3c9d884095fe9b4e09ab2d7045712463ed
          repoUrl: https://github.com/kyma-project/telemetry-manager
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/subprojects
          value: "false"
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: '**/test/**,**/*_test.go'
          version: v1
        name: module-sources
        type: git
        version: 1.0.0
      version: 1.0.0
    meta:
      schemaVersion: v2
```
