### ISSUE TITLE
make install is broken

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/lifecycle-manager#894]
**Description**

The `make install` target renders an incorrect YAML.
an example:
```
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
    controller-gen.kubebuilder.io/version: v0.11.2
  name: kymas.operator.kyma-project.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: webhook-service
          namespace: system
          path: /convert
      conversionReviewVersions:
      - v1
  group: operator.kyma-project.io
```
You can see that `cert-manager.io/inject-ca-from` annotation value is not resolved properly - placeholders are still visible.
In addition you can see `namespace: system` in the webhook configuration. This namespace comes from the Kubebuilder default generator and should be replaced with `kcp-system` or some other valid namespace.

To explain the bug let's focus on the `namespace` value.
The bug exists because the `config/crd` kustomization is just a component.
The component provides valid configuration for the `namespace` transformer, but doesn't actually enable it. It is expected that the "master" kustomization, that includes `config/crd` enables the `namespace` transformer and provides a value for the namespace.

Now the Makefile in the `install` target just renders `config/crd` directly. Because the `namespace` transformer is not enabled, namespace substitution doesn't happen and we can see the invalid result.

This bug is not critical, and wasn't observed so far, because usually, just after `make install`, the developer executes `make deploy`. The `deploy` target uses `config/default` kustomization that **enables** `namespace` transformer (with a value `kcp-system`) and includes `config/crd` component. So all the objects are re-rendered correctly and applied to the cluster, essentially "fixing" the broken `make install` results.
The same happens in case of the `config/control-plane` kustomization - it also renders  correctly because it enables the `namespace` transformer.

**Expected result**
`make install` works correctly

**Actual result**
`make install` produces invalid YAML manifests

**Steps to reproduce**

- modify Makefile so that `install` target doesn't apply manifest to the cluster, just print it out to the screen
- `make install` | less

**Troubleshooting**
n/a
