### ISSUE TITLE
Enable Watcher on Prod

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#943]
### Description

Watcher is currently enabled on STAGE and DEV - we now also need to enable it on Prod.

### Acceptance Criteria

- [x] Enabled Watcher on Prod
    - [x] Contact SRE regarding Release cycle and align the release with them
- [x] Adapt STAGE and DEV Kustomize in management-plane-charts repo
- [x] Introduce Watcher as component in [control-plane Kustomize ](https://github.com/kyma-project/lifecycle-manager/blob/9db7bfa280f255841c50360d091a88e108796803/config/control-plane/kustomization.yaml#L34)
- [x] Adapt `watcher-local-setup` Kustomize
- [x] Verify Watcher working on PROD
- [x] **After** verifying Watcher works as expected: Set kyma-success-intervall to 5min for PROD
- [x] Add Gateway patch to PROD Kustomize 
```yaml
  - patch: |-
      - op: replace
        path: /spec/servers/0/hosts/0
        value: listener.cp.kyma.cloud.sap
      - op: replace
        path: /metadata/namespace
        value: kcp-system
    target:
      kind: Gateway
      name: lifecycle-manager-watcher-gateway
```
- [ ] Add certificate patch to PROD Kustomize
```yaml
 - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: listener.cp.kyma.cloud.sap
      - op: replace
        path: /spec/issuerRef/name
        value: watcher-selfsigned-cluster-issuer
    target:
      kind: Certificate
      name: watcher-serving-cert
```
