### ISSUE TITLE
Extract GH-Actions scripts into own files

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#945]
### Description

Currently, our GH-Actions workflows are each defined in one single file. Since we switched fully to GH-Actions and are now coming up with more and more test cases, the workflow files are getting quite heavy.

Let`s make them more easy readable by seperating the workflow from the actual logic from each step.

Example
```yaml
- name: Create Template Operator Module
        working-directory: ./template-operator
        if: ${{ matrix.e2e-test == 'non-blocking-deletion' }}
        run: |
            $PATH_TO_SCRIPTS/deploy_module.sh
```

### Reasons

- Easy to read
- Better to maintain

### Acceptance Criteria

- [ ] Have Action step scripts in dedicated files and directory
    - Should be placed in .github/workflows/scripts/e2e
- [ ] Clean up all current workflows
- [ ] Refactor script functions to be reusable
