### ISSUE TITLE
KCP SyncResource

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#991]
Created on 2023-10-30 by Xin Ruan (@ruanxin)

## Decision log

| Name               | Description            |
| ------------------ | ---------------------- |
| Title              | KCP SyncResource      |
| Due date           | 2023-11-30             |
| Status             | Proposed on 2023-10-30 |
| Decision type      | Binary                 |
| Affected decisions | -                      |

## Context

Several modules need to create some resources in managed Kyma Runtimes based on the control plane contexts. However, in order to avoid introducing more central components to directly connect to remote clusters, optimize the number of connections, and maintain the principle of least privilege, where only a few central components have admin permissions to access remote clusters, we should provide a way for relies on one centralized component to push those resources to Kyma Runtimes.

## Decision

- Introduce a Custom Resource (CR) to persist resources' content as Kubernetes manifest YAML.
- The central component (lifecycle manager) needs to watch this CR. When a new CR is created or updated, the lifecycle manager should apply it to the relevant remote Kyma Runtime.
- **Sensitive data is not allowed to be delivered by this revision of `SyncResource`, the data encryption at rest solution should be further designed as a prerequisite.**
- [TODO]: add guideline for module CR status update

### KCP SyncResource example:

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: SyncResource
metadata:
  labels:
    "operator.kyma-project.io/kyma-name": [related kyma name]
  name: [unique name indicates the resource to be synced]
  namespace: kcp-system
spec:
  kyma: [related kyma name]
  items:
  - strategy: CreateAndSync
     name: config-update
     resource: |
        apiVersion: v1
        kind: Configmap
        metadata:
            name: config-update
            namespace: kyma-system
        data:
            update.properties |
                foo=bar
  - strategy: Delete
     name: config-to-deleted
     resource: |
      apiVersion: v1
      kind: Configmap
      metadata:
          name: some-config
          namespace: kyma-system
  - strategy: CreateAndSync
     name: module-cr
     subresource: |
        apiVersion: operator.kyma-project.io/v1alpha1
        kind: SomeModule
        metadata:
            name: module-cr-name
            namespace: kyma-system
        status:
          ...
          state: Ready
  - strategy: CreateAndIgnore
    name: some-deployment
    resource: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
          name: app
          namespace: kyma-system
      spec:
          ....
Status:
  conditions:
  - lastTransitionTime: "2023-10-30T15:56:31Z"
    message: resources are synced
    reason: Ready
    status: True
    type: Resources
  lastOperation:
    lastUpdateTime: "2023-10-30T15:56:31Z"
    operation: 'all resources successfully synced to skr'
  state: Ready
  items:
  - name: config-update
     state: Ready
     message: resource has been synced
  - name: config-to-deleted
     state: Ready
     message: resource has been deleted
  - name: module-cr
     state: Ready
     message: resource has been synced
  - name: some-deployment
     state: Ready
     message: resource has been synced
```

### KCP SyncResource explain:

- `operator.kyma-project.io/kyma-name` label enables the lifecycle manager to identify the target Kyma Runtime for deploying the resource.

-  `spec.kyma` mandatory, specifies the target Kyma name for deploying this resource.
- `spec.items` mandatory, specifies a list of resources to be synced
  - `strategy` mandatory, defines the sync strategy
    - `CreateAndSync`: the resources designed as immutable resources for SKR cluster, any modification to the resources by users should be reset.
    - `Delete`: the resources previously deployed in SKR cluster, but should be removed now, this is useful for the scenario to cleanup some old resources.
    - `CreateAndIgnore`: the resources designed as mutable resources for SKR cluster, LM only take care of creating this resource, and recreate it if deleted by users, but any update to the deployed resources in SKR cluster will be ignored.
  -  `name`: mandatory, the name of this resource, not necessary same as actual resource name deployed in SKR cluster.
  - `resource` optional, contains the resource YAML content as plain text.
  - `subresource` optional, contains the subresource YAML content as plain text.
- `status.conditions` and `status.lastOperation` indicate the synchronization status and provide information about the last operation performed by the lifecycle manager.
- `status.state` reflects the current state of the sync resource.
- `status.items` indicates the status of the current list of Resources been synced.

## Consequences

- Establishes a centralized mechanism and utilizes an existing component (lifecycle manager) for managing and syncing resources to remote Kyma Runtimes, reducing the need for direct connections and enhancing security.
- Provides a standardized format (`SyncResource`) for defining resources as Kubernetes manifests.
- Simplifies resource creation and testing for module teams using the Kyma CLI.

### Risks:

- Misconfigurations in the `SyncResource` could lead to synchronization problems or resource mismanagement.

**Comment by pbochynski** [comment]
Some feedback:
1. We need some identifier of SKR. Is it `operator.kyma-project.io/kyma-name` label?
2. What is `spec.channel` for? That resource should be independent of the channel.

**Comment by ruanxin** [comment]
> Some feedback:
> 
> 1. We need some identifier of SKR. Is it `operator.kyma-project.io/kyma-name` label?
Depends on the purpose of the identifier, if you want to indicate something like SKR shoot name, then it's not. This label is the Kyma CR name, which is one-to-one mapped with SKR cluster, it's also used for LM to identify the SKR cluster kubeconfig secret.

In current Kyma CR, we have following labels for indicate SKR cluster, but they are not create or used by LM, if you need similar label used for other services, we can also add them.
```
  labels:
    kyma-project.io/runtime-id: 6ca8a6ea-37b3-47f4-a2c8-fe1b6013db23
    kyma-project.io/shoot-name: f1b6307
    kyma-project.io/subaccount-id: 19ea2000-865d-42fd-8d6f-3e3e2dcce3c8
```
  
> 2. What is `spec.channel` for? That resource should be independent of the channel.
The purpose of this `channel` is just want to consistent with module template. For instance, do we have the use case that some module introduces this kind of resources in new version, and this version first released in `fast` channel, then released to `regular` channel. In this case, this resource should have an identifier for channel, or it's completely independent?

**Comment by kwiatekus** [comment]
@ruanxin How would the submission process of manifest content look like in case of mandatory modules that need to synced across all remote runtimes?

**Comment by kwiatekus** [comment]
@ruanxin If the resource manifests are removed from the content of Sync Object, would lifecycle manager remove the resources on the remote clusters?

**Comment by kwiatekus** [comment]
@janmedrek @ruanxin 
Lets clarify if the mandatory module case would fit into the implementation of the KCP Sync Object

**Comment by ruanxin** [comment]
> @ruanxin How would the submission process of manifest content look like in case of mandatory modules that need to synced across all remote runtimes?

Currently, in my mind, this idea is more suitable for serving some dynamic content which based on each individual skr cluster, for example, some resources contain skr specific data. So it requires a component in KCP which can generate this resource on the fly, LM just take responsibility to sync it. But for your case, if all resources are identical, it's more relavent to put it in the module template. If you just submit it once, there is no such component recreate it when module disabled and enabled again.

> @ruanxin If the resource manifests are removed from the content of Sync Object, would lifecycle manager remove the resources on the remote clusters?

Yes, LM take care the synchronize of this object.

**Comment by ruanxin** [comment]
# Use case

- [ ] KEB installs secret for BTP service operator
- [ ] compass manager needs to propagate a secret for the runtime agent
- [ ]The NFS storage controller needs to create a storage class and persistent volume
- [ ]The warden needs to create a deployment and service account and role

**Comment by PK85** [comment]
Details about: "KEB installs secret for BTP service operator:

1) KEB receives credentials from ERS during Kyma provisioning or update
2) KEB applies a secret with credentials from ERS + generated by KEB clusterID. [Example](https://github.com/kyma-project/btp-manager/blob/main/examples/btp-manager-secret.yaml)
3) some KEB k8s jobs manage that secret. That means once a day it checks if all SKRs have a secret in, if not apply it again.

**Comment by ruanxin** [comment]
Hi @PK85,
> KEB applies a secret with credentials from ERS + generated by KEB clusterID. [Example](https://github.com/kyma-project/btp-manager/blob/main/examples/btp-manager-secret.yaml)

What was the contract data from KEB to ERS to fetch this credential?  is it something you can get from current Kyma CR?
we have some labels defined in Kyma CR contains some data, e.g:
```
    labels:
      kyma-project.io/broker-plan-id: xxx
      kyma-project.io/broker-plan-name: azure
      kyma-project.io/global-account-id: xxx
      kyma-project.io/instance-id: xxx
      kyma-project.io/platform-region: cf-eu20
      kyma-project.io/region: northeurope
      kyma-project.io/runtime-id: xxx
      kyma-project.io/shoot-name: xxx
      kyma-project.io/subaccount-id: ""
```
are they contain the required data?

**Comment by PK85** [comment]
KEB is not fetching credentials, KEB receives credentials when ERS is calling KEB to spin a Kyma cluster. Nope, those labels are not related to those credentials.

**Comment by ravi-shankar-sap** [comment]
@ruanxin, Based on our understanding, the Kyma CR implementation will also be enhanced to include the contents of `Module CR` spec in the status. We had following questions related to `SyncResource CR` and `Kyma CR` changes:

1. How LM will learn which Module CR(s) to be monitored and included in Kyma CR.status?
2. Will the Module CR spec in the KymaCR.status single object containing the last modified CR or a list containing all the changes?
            2a.    If it is a single object, is there a possibility of losing concurrent updates to multiple watched CRs in SKR?
            2b.    If it is a list, how and when the objects will get removed from the list?
            2c.    If they don’t get removed from the list, should the KCP modules maintain some kind of state to track what has changed from previous reconcile?
3. Can the SyncResource be used to update the contents of the Module CR in SKR?
4. Assuming the SyncResource example above is already deployed, is the changes to `resource.spec` tracked only by the changes to the keys (resource file name) or by the changes to the contents as well? Answers to below questions may help:
        4a.   If the KCP Module Manager updates the SyncResource CR and removes the `secret.yaml` from it, will the secret `some-credential` be deleted from SKR?
       4b.   If the KCP Module Manager updates the SyncResource CR and changes the secret name to `some-credential-1`, will the secret `some-credential` be deleted and `some-credential-1` be created?

**Comment by a-thaler** [comment]
In your example you outline that transporting a secret is a common use case. The kind Secret is special in kubernetes in regards on how the data gets stored in the APIServer. Embedding a secret inside a CR will not fullfil these requirements coming with secrets, as the APIServer will not treat the data special anymore. So it must be checked if the solution is acceptable for secret data at all, or what kind of limitations that will imply.
Maybe the secret data can be stored as a real secret in KCP and just referenced by the SyncResource? Is it really needed to embed the data?

**Comment by pbochynski** [comment]
As discussed today the sample scenario can look like this.


1. User installs Infrastructure module with default CR that will have empty spec. Next, the user will 
add VPC peering and NFS volumes to the spec.

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Infrastructure
metadata:
  name: default
  namespace: kyma-system
spec:
  vpcPeerings:
    - name: peering-1
      description: peering-1
      remoteVpcId: vpc-1
      remoteRegion: eu-central-1
      remoteCidrRange:
    - name: peering-2
      description: peering-2
      remoteVpcId: vpc-2
      remoteRegion: eu-central-1
      remoteCidrRange:
  nfsVolumes:
    - name: nfs-1
      description: nfs-1
      size: 100Gi
    - name: nfs-2
      description: nfs-2
      size: 100Gi

```

2. The Kyma Lifecycle Manager will include the Infrastructure CR in the Kyma CR status in the Kyma Control Plane.

3. Infrastructure Manager controllers deployed in the KCP are watching for the Kyma CR status changes and create
the VPC peering and NFS volumes custom resources in the Kyma Control Plane. These resources will be reconciled and 
will create the corresponding resources in the cloud provider account. As a result, SyncResource CRs will be created
to create the corresponding resources in the SKR cluster (storage class, persistent volume etc).
```
apiVersion: operator.kyma-project.io/v1alpha1
kind: SyncResource
metadata:
  namespace: nfs-manager
  name: kyma-1233445345345
spec:
  kyma: kyma-1233445345345
  resource:
  - strategy: CreateAndSync
    name: nfs-1-pv
    resource: |
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
        name: pv-nfs
      spec:
        capacity:
          storage: 10Gi
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs-csi
        mountOptions:
          - nfsvers=3
        csi:
          driver: nfs.csi.k8s.io
          readOnly: false
          # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
          # make sure this value is unique for every share in the cluster
          volumeHandle: 10.17.65.170#ssd#pvc1##
          volumeAttributes:
            server: 10.17.65.170
            share: /ssd
  - strategy: CreateAndSync
    name: nfs-1-pvc
    resource: |
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: pvc-nfs-static
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        volumeName: pv-nfs
        storageClassName: nfs-csi
  - strategy: CreateAndSync
    name: nfs-1-sc
    resource: |
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: nfs-csi
      provisioner: nfs.csi.k8s.io
      parameters:
        server: 10.17.65.170
        share: /ssd
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=3

**Comment by pbochynski** [comment]
@ruanxin Some additional aspect that came from discussion with the interested teams:

There is a case where module does not have an active component in the SKR. The manager is running in the KCP and wants to set the status of the module CR. The status is a subresource in kubernetes so it can be updated independently from spec, so I think it would be nice to provide a syntax to update status subresource.

**Comment by ruanxin** [comment]
Hi @pbochynski ,
> There is a case where module does not have an active component in the SKR. The manager is running in the KCP and wants to set the status of the module CR. The status is a subresource in kubernetes so it can be updated independently from spec, so I think it would be nice to provide a syntax to update status subresource.

Is the usage just for updating Module CR status? or it need to support all resources subresource? The thing is `status` is just a common name for subresource, but kubernate allows to define subresource with any name.

But the SyncResource definition can be extended as follows:
```
  resources:
  - strategy: CreateAndSync
     name: module-cr
     resource: |
         apiVersion: operator.kyma-project.io/v1alpha1
         kind: SomeModule
         metadata:
            name: module-cr-name
         spec:
            ...
    subresource: |
        status:
          ...
          state: Ready
```
One thing I want to address here is if we allow update subresources, it really needs the Module team to take care of the frequency of updating the subresources, it should prevent updating SyncResource if the status is not changed, otherwise, it will significantly increase the amount of traffic for sync module status.
